// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ListAccountsV1 get user accounts.
func (c *Client) ListAccountsV1(ctx context.Context, sort []string, filter string) ([]UserAccount, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]UserAccount, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/accounts"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int           `json:"totalCount"`
			Results    []UserAccount `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateAccountV1 adds new account.
func (c *Client) CreateAccountV1(ctx context.Context, request *UserAccount) (*UserAccount, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result UserAccount
	endpoint := prefix + "/accounts"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateAccountV1: %w", err)
	}
	return &result, nil
}

// GetAccountV1 gets the user account.
func (c *Client) GetAccountV1(ctx context.Context, id string) (*UserAccount, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result UserAccount
	endpoint := fmt.Sprintf("%s/accounts/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetAccountV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteAccountV1 deletes the user account.
func (c *Client) DeleteAccountV1(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/accounts/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteAccountV1(%s): %w", id, err)
	}
	return nil
}

// ResolveAccountV1IDByName looks up a AccountV1 by its username field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveAccountV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	listPath := prefix + "/accounts"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "username", "username", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveAccountV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveAccountV1ByName looks up a AccountV1 by its username field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveAccountV1ByName(ctx context.Context, name string) (*UserAccount, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	listPath := prefix + "/accounts"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "username", "username", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveAccountV1ByName(%s): %w", name, err)
	}
	var out UserAccount
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveAccountV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}
