// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// CreateAdcsSettingsV1 create AD CS Settings configuration for either inbound or outbound mode.
//
// Required privileges: create:pro:ad-cs-settings. Legacy Jamf Pro privilege name(s): Create AD CS Settings.
func (c *Client) CreateAdcsSettingsV1(ctx context.Context, request *AdcsSettings) (*HrefResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result HrefResponse
	endpoint := prefix + "/pki/adcs-settings"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateAdcsSettingsV1: %w", err)
	}
	return &result, nil
}

// ValidateAdcsCertificateV1 validate AD CS Settings server certificate.
//
// Required privileges: update:pro:ad-cs-settings, create:pro:ad-cs-settings. Legacy Jamf Pro privilege name(s): Update AD CS Settings, Create AD CS Settings.
// The Jamf API spec does not encode whether these are required together or as alternatives.
func (c *Client) ValidateAdcsCertificateV1(ctx context.Context, request *AdcsCertificate) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := prefix + "/pki/adcs-settings/validate-certificate"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("ValidateAdcsCertificateV1: %w", err)
	}
	return nil
}

// ValidateAdcsClientCertificateV1 validate AD CS Settings client certificate.
//
// Required privileges: update:pro:ad-cs-settings, create:pro:ad-cs-settings. Legacy Jamf Pro privilege name(s): Update AD CS Settings, Create AD CS Settings.
// The Jamf API spec does not encode whether these are required together or as alternatives.
func (c *Client) ValidateAdcsClientCertificateV1(ctx context.Context, request *AdcsCertificate) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := prefix + "/pki/adcs-settings/validate-client-certificate"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("ValidateAdcsClientCertificateV1: %w", err)
	}
	return nil
}

// GetAdcsSettingsV1 get AD CS Settings configuration for the ID value.
//
// Required privileges: read:pro:ad-cs-settings. Legacy Jamf Pro privilege name(s): Read AD CS Settings.
func (c *Client) GetAdcsSettingsV1(ctx context.Context, id string) (*AdcsSettingsResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result AdcsSettingsResponse
	endpoint := fmt.Sprintf("%s/pki/adcs-settings/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetAdcsSettingsV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteAdcsSettingsV1 delete AD CS Settings configuration by ID.
//
// Required privileges: delete:pro:ad-cs-settings. Legacy Jamf Pro privilege name(s): Delete AD CS Settings.
func (c *Client) DeleteAdcsSettingsV1(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/pki/adcs-settings/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteAdcsSettingsV1(%s): %w", id, err)
	}
	return nil
}

// UpdateAdcsSettingsV1 update AD CS Settings configuration.
//
// Required privileges: update:pro:ad-cs-settings. Legacy Jamf Pro privilege name(s): Update AD CS Settings.
func (c *Client) UpdateAdcsSettingsV1(ctx context.Context, id string, request *AdcsSettings) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/pki/adcs-settings/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPatch, endpoint, request, "application/merge-patch+json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("UpdateAdcsSettingsV1(%s): %w", id, err)
	}
	return nil
}

// GetAdcsSettingsDependenciesV1 retrieve list of AD CS Settings dependencies.
//
// Required privileges: read:pro:ad-cs-settings. Legacy Jamf Pro privilege name(s): Read AD CS Settings.
func (c *Client) GetAdcsSettingsDependenciesV1(ctx context.Context, id string) (*AdcsDependencies, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result AdcsDependencies
	endpoint := fmt.Sprintf("%s/pki/adcs-settings/%s/dependencies", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetAdcsSettingsDependenciesV1(%s): %w", id, err)
	}
	return &result, nil
}

// ListAdcsSettingsHistoryV1 get specified AD CS Settings history object.
//
// Required privileges: read:pro:ad-cs-settings. Legacy Jamf Pro privilege name(s): Read AD CS Settings.
func (c *Client) ListAdcsSettingsHistoryV1(ctx context.Context, id string, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/pki/adcs-settings/%s/history", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateAdcsSettingsHistoryNoteV1 add specified AD CS Settings object note.
//
// Required privileges: update:pro:ad-cs-settings. Legacy Jamf Pro privilege name(s): Update AD CS Settings.
func (c *Client) CreateAdcsSettingsHistoryNoteV1(ctx context.Context, id string, request *ObjectHistoryNote) (*HrefResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result HrefResponse
	endpoint := fmt.Sprintf("%s/pki/adcs-settings/%s/history", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateAdcsSettingsHistoryNoteV1(%s): %w", id, err)
	}
	return &result, nil
}
