// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ListApiIntegrationsV1 get the current API Integrations.
func (c *Client) ListApiIntegrationsV1(ctx context.Context, sort []string, filter string) ([]ApiIntegrationResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]ApiIntegrationResponse, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/api-integrations"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                      `json:"totalCount"`
			Results    []ApiIntegrationResponse `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateApiIntegrationV1 create API integration object.
func (c *Client) CreateApiIntegrationV1(ctx context.Context, request *ApiIntegrationRequest) (*ApiIntegrationResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result ApiIntegrationResponse
	endpoint := prefix + "/api-integrations"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("CreateApiIntegrationV1: %w", err)
	}
	return &result, nil
}

// GetApiIntegrationV1 get specified API integration object.
func (c *Client) GetApiIntegrationV1(ctx context.Context, id string) (*ApiIntegrationResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result ApiIntegrationResponse
	endpoint := fmt.Sprintf("%s/api-integrations/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetApiIntegrationV1(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateApiIntegrationV1 update specified API integration object.
func (c *Client) UpdateApiIntegrationV1(ctx context.Context, id string, request *ApiIntegrationRequest) (*ApiIntegrationResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result ApiIntegrationResponse
	endpoint := fmt.Sprintf("%s/api-integrations/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateApiIntegrationV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteApiIntegrationV1 remove specified API integration.
func (c *Client) DeleteApiIntegrationV1(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/api-integrations/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteApiIntegrationV1(%s): %w", id, err)
	}
	return nil
}

// RotateApiIntegrationClientCredentialsV1 create client credentials for specified API integration.
func (c *Client) RotateApiIntegrationClientCredentialsV1(ctx context.Context, id string) (*OAuthClientCredentials, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result OAuthClientCredentials
	endpoint := fmt.Sprintf("%s/api-integrations/%s/client-credentials", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodPost, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("RotateApiIntegrationClientCredentialsV1(%s): %w", id, err)
	}
	return &result, nil
}

// ResolveApiIntegrationV1IDByName looks up a ApiIntegrationV1 by its displayName field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveApiIntegrationV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	listPath := prefix + "/api-integrations"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "displayName", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveApiIntegrationV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveApiIntegrationV1ByName looks up a ApiIntegrationV1 by its displayName field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveApiIntegrationV1ByName(ctx context.Context, name string) (*ApiIntegrationResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	listPath := prefix + "/api-integrations"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "displayName", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveApiIntegrationV1ByName(%s): %w", name, err)
	}
	var out ApiIntegrationResponse
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveApiIntegrationV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}
