// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"net/http"
	"testing"
)

func TestListAppInstallerDeploymentsV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/app-installers/deployments", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{
			"results":    []map[string]any{{}},
			"totalCount": 1,
			"hasNext":    false,
		})
	})

	results, err := c.ListAppInstallerDeploymentsV1(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if len(results) != 1 {
		t.Fatalf("len = %d, want 1", len(results))
	}
}

func TestCreateAppInstallerDeploymentV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/app-installers/deployments", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		writeJSON(t, w, http.StatusCreated, map[string]any{})
	})

	result, err := c.CreateAppInstallerDeploymentV1(context.Background(), &AppInstallerDeployment{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetAppInstallerDeploymentV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/app-installers/deployments/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{})
	})

	result, err := c.GetAppInstallerDeploymentV1(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetAppInstallerDeploymentV1_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/app-installers/deployments/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(t, w, http.StatusNotFound, map[string]any{
			"httpStatus": 404,
			"traceId":    "trace-nf",
			"errors":     []map[string]string{{"code": "NOT_FOUND", "field": "id", "description": "not found"}},
		})
	})

	_, err := c.GetAppInstallerDeploymentV1(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestUpdateAppInstallerDeploymentV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/app-installers/deployments/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPut {
			t.Errorf("method = %s, want PUT", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{})
	})

	result, err := c.UpdateAppInstallerDeploymentV1(context.Background(), "test-id", &AppInstallerDeployment{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestDeleteAppInstallerDeploymentV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/app-installers/deployments/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(http.StatusNoContent)
	})

	err := c.DeleteAppInstallerDeploymentV1(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
}

func TestResolveAppInstallerDeploymentV1IDByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/app-installers/deployments", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{
			"results": []map[string]any{
				{"id": "resolved-id", "name": "target"},
			},
			"totalCount": 1,
		})
	})

	id, err := c.ResolveAppInstallerDeploymentV1IDByName(context.Background(), "target")
	if err != nil {
		t.Fatal(err)
	}
	if id != "resolved-id" {
		t.Errorf("id = %q, want resolved-id", id)
	}
}

func TestResolveAppInstallerDeploymentV1ByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/app-installers/deployments", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{
			"results": []map[string]any{
				{"id": "resolved-id", "name": "target"},
			},
			"totalCount": 1,
		})
	})

	result, err := c.ResolveAppInstallerDeploymentV1ByName(context.Background(), "target")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestApplyAppInstallerDeploymentV1_Create(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	// List and create share the same path — single handler dispatches on method.
	mux.HandleFunc("/api/pro/v1/tenant/t-test/app-installers/deployments", func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			writeJSON(t, w, http.StatusOK, map[string]any{
				"results":    []any{},
				"totalCount": 0,
			})
		case http.MethodPost:
			writeJSON(t, w, 201, map[string]any{
				"id":   "new-id",
				"href": "/new-id",
			})
		default:
			t.Errorf("unexpected method %s", r.Method)
		}
	})

	id, created, err := c.ApplyAppInstallerDeploymentV1(context.Background(), &AppInstallerDeployment{Name: ptrStr("target")})
	if err != nil {
		t.Fatal(err)
	}
	if !created {
		t.Error("expected created = true")
	}
	if id != "new-id" {
		t.Errorf("id = %q, want new-id", id)
	}
}

func TestApplyAppInstallerDeploymentV1_Update(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	// List returns a match → resolver succeeds → apply updates.
	mux.HandleFunc("/api/pro/v1/tenant/t-test/app-installers/deployments", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{
			"results": []map[string]any{
				{"id": "existing-id", "name": "target"},
			},
			"totalCount": 1,
		})
	})
	mux.HandleFunc("/api/pro/v1/tenant/t-test/app-installers/deployments/existing-id", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(t, w, 200, map[string]any{"id": "existing-id"})
	})

	id, created, err := c.ApplyAppInstallerDeploymentV1(context.Background(), &AppInstallerDeployment{Name: ptrStr("target")})
	if err != nil {
		t.Fatal(err)
	}
	if created {
		t.Error("expected created = false")
	}
	if id != "existing-id" {
		t.Errorf("id = %q, want existing-id", id)
	}
}
