// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
)

// GetCacheSettingsV1 get Cache Settings.
//
// Required privileges: cache:read. Legacy Jamf Pro privilege name(s): Read Cache.
func (c *Client) GetCacheSettingsV1(ctx context.Context) (*CacheSettings, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result CacheSettings
	endpoint := prefix + "/cache-settings"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetCacheSettingsV1: %w", err)
	}
	return &result, nil
}

// UpdateCacheSettingsV1 update Cache Settings.
//
// Required privileges: cache:update. Legacy Jamf Pro privilege name(s): Update Cache.
func (c *Client) UpdateCacheSettingsV1(ctx context.Context, request *CacheSettings) (*CacheSettings, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result CacheSettings
	endpoint := prefix + "/cache-settings"
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateCacheSettingsV1: %w", err)
	}
	return &result, nil
}
