// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetActiveCertificateAuthorityV1 returns X.509 details of the active Certificate Authority (CA).
func (c *Client) GetActiveCertificateAuthorityV1(ctx context.Context) (*CertificateRecord, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result CertificateRecord
	endpoint := prefix + "/pki/certificate-authority/active"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetActiveCertificateAuthorityV1: %w", err)
	}
	return &result, nil
}

// DownloadActiveCertificateAuthorityDerV1 returns X.509 of active Certificate Authority (CA) in DER format.
func (c *Client) DownloadActiveCertificateAuthorityDerV1(ctx context.Context) ([]byte, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result []byte
	endpoint := prefix + "/pki/certificate-authority/active/der"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("DownloadActiveCertificateAuthorityDerV1: %w", err)
	}
	return result, nil
}

// DownloadActiveCertificateAuthorityPemV1 returns active Certificate Authority (CA) in PEM format.
func (c *Client) DownloadActiveCertificateAuthorityPemV1(ctx context.Context) ([]byte, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result []byte
	endpoint := prefix + "/pki/certificate-authority/active/pem"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("DownloadActiveCertificateAuthorityPemV1: %w", err)
	}
	return result, nil
}

// GetCertificateAuthorityV1 returns X.509 details of Certificate Authority (CA) with provided ID.
func (c *Client) GetCertificateAuthorityV1(ctx context.Context, id string) (*CertificateRecord, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result CertificateRecord
	endpoint := fmt.Sprintf("%s/pki/certificate-authority/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetCertificateAuthorityV1(%s): %w", id, err)
	}
	return &result, nil
}

// DownloadCertificateAuthorityDerV1 returns X.509 current Certificate Authority (CA) with provided ID in DER format.
func (c *Client) DownloadCertificateAuthorityDerV1(ctx context.Context, id string) ([]byte, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result []byte
	endpoint := fmt.Sprintf("%s/pki/certificate-authority/%s/der", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("DownloadCertificateAuthorityDerV1(%s): %w", id, err)
	}
	return result, nil
}

// DownloadCertificateAuthorityPemV1 returns current Certificate Authority (CA) with provided ID in PEM format.
func (c *Client) DownloadCertificateAuthorityPemV1(ctx context.Context, id string) ([]byte, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result []byte
	endpoint := fmt.Sprintf("%s/pki/certificate-authority/%s/pem", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("DownloadCertificateAuthorityPemV1(%s): %w", id, err)
	}
	return result, nil
}
