// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ListCloudIdpV1 get information about all Cloud Identity Providers configurations.
func (c *Client) ListCloudIdpV1(ctx context.Context, sort []string) ([]CloudIDPCommonResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]CloudIDPCommonResponse, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}

		endpoint := prefix + "/cloud-idp"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                      `json:"totalCount"`
			Results    []CloudIDPCommonResponse `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// ExportCloudIdpV1 export Cloud Identity Providers collection.
func (c *Client) ExportCloudIdpV1(ctx context.Context, request *ExportParameters, exportFields []string, exportLabels []string, sort []string, filter string) ([]byte, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result []byte
	endpoint := prefix + "/cloud-idp/export"
	params := url.Values{}
	if len(exportFields) > 0 {
		params.Set("export-fields", strings.Join(exportFields, ","))
	}
	if len(exportLabels) > 0 {
		params.Set("export-labels", strings.Join(exportLabels, ","))
	}
	if len(sort) > 0 {
		params.Set("sort", strings.Join(sort, ","))
	}
	if filter != "" {
		params.Set("filter", filter)
	}
	if encoded := params.Encode(); encoded != "" {
		endpoint += "?" + encoded
	}
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("ExportCloudIdpV1: %w", err)
	}
	return result, nil
}

// GetCloudIdpV1 get Cloud Identity Provider configuration with given ID.
func (c *Client) GetCloudIdpV1(ctx context.Context, id string) (*CloudIDPCommon, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result CloudIDPCommon
	endpoint := fmt.Sprintf("%s/cloud-idp/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetCloudIdpV1(%s): %w", id, err)
	}
	return &result, nil
}

// ListCloudIdpHistoryV1 get Cloud Identity Provider history.
func (c *Client) ListCloudIdpHistoryV1(ctx context.Context, id string, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/cloud-idp/%s/history", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateCloudIdpHistoryNoteV1 add Cloud Identity Provider history note.
func (c *Client) CreateCloudIdpHistoryNoteV1(ctx context.Context, id string, request *ObjectHistoryNote) (*ObjectHistory, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result ObjectHistory
	endpoint := fmt.Sprintf("%s/cloud-idp/%s/history", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateCloudIdpHistoryNoteV1(%s): %w", id, err)
	}
	return &result, nil
}

// TestCloudIdpGroupV1 get group test search.
func (c *Client) TestCloudIdpGroupV1(ctx context.Context, id string, request *GroupTestSearchRequest) (*GroupTestSearchResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result GroupTestSearchResponse
	endpoint := fmt.Sprintf("%s/cloud-idp/%s/test-group", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("TestCloudIdpGroupV1(%s): %w", id, err)
	}
	return &result, nil
}

// TestCloudIdpUserV1 get user test search.
func (c *Client) TestCloudIdpUserV1(ctx context.Context, id string, request *UserTestSearchRequest) (*UserTestSearchResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result UserTestSearchResponse
	endpoint := fmt.Sprintf("%s/cloud-idp/%s/test-user", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("TestCloudIdpUserV1(%s): %w", id, err)
	}
	return &result, nil
}

// TestCloudIdpUserMembershipV1 get membership test search.
func (c *Client) TestCloudIdpUserMembershipV1(ctx context.Context, id string, request *MembershipTestSearchRequest) (*MembershipTestSearchResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result MembershipTestSearchResponse
	endpoint := fmt.Sprintf("%s/cloud-idp/%s/test-user-membership", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("TestCloudIdpUserMembershipV1(%s): %w", id, err)
	}
	return &result, nil
}

// ResolveCloudIdpV1IDByName looks up a CloudIdpV1 by its displayName field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveCloudIdpV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	listPath := prefix + "/cloud-idp"
	id, _, err := c.transport.ResolveByNameClientPaged(ctx, listPath, "", "", "displayName", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveCloudIdpV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveCloudIdpV1ByName looks up a CloudIdpV1 by its displayName field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveCloudIdpV1ByName(ctx context.Context, name string) (*CloudIDPCommonResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	listPath := prefix + "/cloud-idp"
	_, raw, err := c.transport.ResolveByNameClientPaged(ctx, listPath, "", "", "displayName", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveCloudIdpV1ByName(%s): %w", name, err)
	}
	var out CloudIDPCommonResponse
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveCloudIdpV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}
