// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// GetAllComputerPrestageScopeV2 get all device Scope for all Computer Prestages.
func (c *Client) GetAllComputerPrestageScopeV2(ctx context.Context) (*PrestageScopeV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result PrestageScopeV2
	endpoint := prefix + "/computer-prestages/scope"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetAllComputerPrestageScopeV2: %w", err)
	}
	return &result, nil
}

// GetComputerPrestageScopeV2 get device Scope for a specific Computer Prestage.
func (c *Client) GetComputerPrestageScopeV2(ctx context.Context, id string) (*PrestageScopeResponseV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result PrestageScopeResponseV2
	endpoint := fmt.Sprintf("%s/computer-prestages/%s/scope", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerPrestageScopeV2(%s): %w", id, err)
	}
	return &result, nil
}

// ReplaceComputerPrestageScopeV2 replace device Scope for a specific Computer Prestage.
func (c *Client) ReplaceComputerPrestageScopeV2(ctx context.Context, id string, request *PrestageScopeUpdate) (*PrestageScopeResponseV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result PrestageScopeResponseV2
	endpoint := fmt.Sprintf("%s/computer-prestages/%s/scope", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("ReplaceComputerPrestageScopeV2(%s): %w", id, err)
	}
	return &result, nil
}

// AddToComputerPrestageScopeV2 add device Scope for a specific Computer Prestage.
func (c *Client) AddToComputerPrestageScopeV2(ctx context.Context, id string, request *PrestageScopeUpdate) (*PrestageScopeResponseV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result PrestageScopeResponseV2
	endpoint := fmt.Sprintf("%s/computer-prestages/%s/scope", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("AddToComputerPrestageScopeV2(%s): %w", id, err)
	}
	return &result, nil
}

// RemoveFromComputerPrestageScopeV2 remove device Scope for a specific Computer Prestage.
func (c *Client) RemoveFromComputerPrestageScopeV2(ctx context.Context, id string, request *PrestageScopeUpdate) (*PrestageScopeResponseV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result PrestageScopeResponseV2
	endpoint := fmt.Sprintf("%s/computer-prestages/%s/scope/delete-multiple", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("RemoveFromComputerPrestageScopeV2(%s): %w", id, err)
	}
	return &result, nil
}

// ListComputerPrestagesV3 get sorted and paged Computer Prestages.
func (c *Client) ListComputerPrestagesV3(ctx context.Context, sort []string) ([]GetComputerPrestageV3, error) {
	prefix := c.transport.TenantPrefix("pro", "v3")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]GetComputerPrestageV3, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}

		endpoint := prefix + "/computer-prestages"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                     `json:"totalCount"`
			Results    []GetComputerPrestageV3 `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateComputerPrestageV3 create a Computer Prestage.
func (c *Client) CreateComputerPrestageV3(ctx context.Context, request *PostComputerPrestageV3) (*HrefResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v3")
	var result HrefResponse
	endpoint := prefix + "/computer-prestages"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateComputerPrestageV3: %w", err)
	}
	return &result, nil
}

// GetComputerPrestageV3 retrieve a Computer Prestage with the supplied id.
func (c *Client) GetComputerPrestageV3(ctx context.Context, id string) (*GetComputerPrestageV3, error) {
	prefix := c.transport.TenantPrefix("pro", "v3")
	var result GetComputerPrestageV3
	endpoint := fmt.Sprintf("%s/computer-prestages/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerPrestageV3(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateComputerPrestageV3 update a Computer Prestage.
func (c *Client) UpdateComputerPrestageV3(ctx context.Context, id string, request *PutComputerPrestageV3) (*GetComputerPrestageV3, error) {
	prefix := c.transport.TenantPrefix("pro", "v3")
	var result GetComputerPrestageV3
	endpoint := fmt.Sprintf("%s/computer-prestages/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateComputerPrestageV3(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteComputerPrestageV3 delete a Computer Prestage with the supplied id.
func (c *Client) DeleteComputerPrestageV3(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("pro", "v3")
	endpoint := fmt.Sprintf("%s/computer-prestages/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteComputerPrestageV3(%s): %w", id, err)
	}
	return nil
}
