// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ListPreviewComputers return a list of Computers.
func (c *Client) ListPreviewComputers(ctx context.Context, sort []string) ([]ComputerOverview, error) {
	prefix := c.transport.TenantPrefix("pro", "")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]ComputerOverview, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}

		endpoint := prefix + "/preview/computers"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                `json:"totalCount"`
			Results    []ComputerOverview `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}
