// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ListDeviceEnrollmentDevicesV1 retrieve a list of Devices assigned to the supplied id.
func (c *Client) ListDeviceEnrollmentDevicesV1(ctx context.Context, id string) (*DeviceEnrollmentDeviceSearchResults, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result DeviceEnrollmentDeviceSearchResults
	endpoint := fmt.Sprintf("%s/device-enrollments/%s/devices", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListDeviceEnrollmentDevicesV1(%s): %w", id, err)
	}
	return &result, nil
}
