// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateDigicertTrustLifecycleManagerV1 create DigiCert Trust Lifecycle Manager configuration with client authentication via client certificate.
//
// Required privileges: create:pro:digicert-settings. Legacy Jamf Pro privilege name(s): Create DigiCert Settings.
func (c *Client) CreateDigicertTrustLifecycleManagerV1(ctx context.Context, request *DigiCertSetting) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result HrefResponse
	endpoint := prefix + "/pki/digicert/trust-lifecycle-manager"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateDigicertTrustLifecycleManagerV1: %w", err)
	}
	return &result, nil
}

// GetDigicertTrustLifecycleManagerV1 retrieve DigiCert Trust Lifecycle Manager configuration.
//
// Required privileges: read:pro:digicert-settings. Legacy Jamf Pro privilege name(s): Read DigiCert Settings.
//
// Parameters:
//   - id: ID of the DigiCert Trust Lifecycle Manager configuration.
func (c *Client) GetDigicertTrustLifecycleManagerV1(ctx context.Context, id string) (*DigiCertSettingResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result DigiCertSettingResponse
	endpoint := fmt.Sprintf("%s/pki/digicert/trust-lifecycle-manager/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDigicertTrustLifecycleManagerV1(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateDigicertTrustLifecycleManagerV1 update DigiCert Trust Lifecycle Manager configuration.
//
// Required privileges: update:pro:digicert-settings. Legacy Jamf Pro privilege name(s): Update DigiCert Settings.
//
// Parameters:
//   - id: ID of the DigiCert Trust Lifecycle Manager configuration.
func (c *Client) UpdateDigicertTrustLifecycleManagerV1(ctx context.Context, id string, request *DigiCertSetting) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/pki/digicert/trust-lifecycle-manager/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPatch, endpoint, request, "application/merge-patch+json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("UpdateDigicertTrustLifecycleManagerV1(%s): %w", id, err)
	}
	return nil
}

// DeleteDigicertTrustLifecycleManagerV1 delete DigiCert Trust Lifecycle Manager configuration.
//
// Required privileges: delete:pro:digicert-settings. Legacy Jamf Pro privilege name(s): Delete DigiCert Settings.
//
// Parameters:
//   - id: ID of the DigiCert Trust Lifecycle Manager configuration.
func (c *Client) DeleteDigicertTrustLifecycleManagerV1(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/pki/digicert/trust-lifecycle-manager/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteDigicertTrustLifecycleManagerV1(%s): %w", id, err)
	}
	return nil
}

// GetDigicertTrustLifecycleManagerConnectionStatusV1 get connection status of DigiCert Trust Lifecycle Manager for a given ID.
//
// Required privileges: read:pro:digicert-settings. Legacy Jamf Pro privilege name(s): Read DigiCert Settings.
//
// Parameters:
//   - id: ID of the DigiCert Trust Lifecycle Manager settings.
func (c *Client) GetDigicertTrustLifecycleManagerConnectionStatusV1(ctx context.Context, id string) (*DigicertConnectionStatus, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result DigicertConnectionStatus
	endpoint := fmt.Sprintf("%s/pki/digicert/trust-lifecycle-manager/%s/connection-status", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDigicertTrustLifecycleManagerConnectionStatusV1(%s): %w", id, err)
	}
	return &result, nil
}

// GetDigicertTrustLifecycleManagerDependenciesV1 retrieve list of DigiCert Trust Lifecycle Manager Settings dependencies.
//
// Required privileges: read:pro:digicert-settings. Legacy Jamf Pro privilege name(s): Read DigiCert Settings.
//
// Parameters:
//   - id: ID of the DigiCert Trust Lifecycle Manager configuration.
func (c *Client) GetDigicertTrustLifecycleManagerDependenciesV1(ctx context.Context, id string) (*DigicertDependencies, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result DigicertDependencies
	endpoint := fmt.Sprintf("%s/pki/digicert/trust-lifecycle-manager/%s/dependencies", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDigicertTrustLifecycleManagerDependenciesV1(%s): %w", id, err)
	}
	return &result, nil
}

// CheckDigicertTrustLifecycleManagerPrivilegesV1 check DigiCert account permissions for certificate deployment.
//
// Required privileges: read:pro:digicert-settings. Legacy Jamf Pro privilege name(s): Read DigiCert Settings.
//
// Parameters:
//   - id: ID of the DigiCert Trust Lifecycle Manager settings.
func (c *Client) CheckDigicertTrustLifecycleManagerPrivilegesV1(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/pki/digicert/trust-lifecycle-manager/%s/privilege-check", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodGet, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("CheckDigicertTrustLifecycleManagerPrivilegesV1(%s): %w", id, err)
	}
	return nil
}

// ValidateDigicertClientCertificateV1 validate DigiCert Trust Lifecycle Manager client certificate.
//
// Required privileges: create:pro:digicert-settings, update:pro:digicert-settings. Legacy Jamf Pro privilege name(s): Create DigiCert Settings, Update DigiCert Settings.
// The Jamf API spec does not encode whether these are required together or as alternatives.
func (c *Client) ValidateDigicertClientCertificateV1(ctx context.Context, request *Certificate) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := prefix + "/pki/digicert/trust-lifecycle-manager/validate-client-certificate"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("ValidateDigicertClientCertificateV1: %w", err)
	}
	return nil
}
