// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
)

// GetEnvironmentTypeV2 get the cloud services environment type.
//
// Required privileges: none (callable by any authenticated API client).
func (c *Client) GetEnvironmentTypeV2(ctx context.Context) (*EnvironmentType, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	var result EnvironmentType
	endpoint := prefix + "/environment-type"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetEnvironmentTypeV2: %w", err)
	}
	return &result, nil
}
