// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ListNotificationsV1 get Notifications for user and site.
func (c *Client) ListNotificationsV1(ctx context.Context) ([]NotificationV1, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result []NotificationV1
	endpoint := prefix + "/notifications"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListNotificationsV1: %w", err)
	}
	return result, nil
}

// DeleteNotificationV1 delete Notifications.
func (c *Client) DeleteNotificationV1(ctx context.Context, notificationType string, id string) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/notifications/%s/%s", prefix, url.PathEscape(notificationType), url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteNotificationV1(%s): %w", notificationType, err)
	}
	return nil
}
