// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"net/http"
	"testing"
)

func TestInitializeSystemV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/system/initialize", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusAccepted)
	})

	err := c.InitializeSystemV1(context.Background(), &InitializeV1{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestPlatformInitializeSystemV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/system/platform-initialize", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusAccepted)
	})

	err := c.PlatformInitializeSystemV1(context.Background(), &PlatformInitializeV1{})
	if err != nil {
		t.Fatal(err)
	}
}
