// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// GetJamfConnectSettingsV1 get the Jamf Connect settings that you have access to see.
func (c *Client) GetJamfConnectSettingsV1(ctx context.Context) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := prefix + "/jamf-connect"
	if err := c.transport.DoExpect(ctx, http.MethodGet, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("GetJamfConnectSettingsV1: %w", err)
	}
	return nil
}

// ListJamfConnectConfigProfilesV1 search for config profiles linked to Jamf Connect.
func (c *Client) ListJamfConnectConfigProfilesV1(ctx context.Context, sort []string, filter string) ([]LinkedConnectProfile, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]LinkedConnectProfile, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/jamf-connect/config-profiles"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                    `json:"totalCount"`
			Results    []LinkedConnectProfile `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// UpdateJamfConnectConfigProfileV1 update the way the Jamf Connect app gets updated on computers within scope of the associated configuration profile.
func (c *Client) UpdateJamfConnectConfigProfileV1(ctx context.Context, id string, request *LinkedConnectProfile) (*LinkedConnectProfile, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result LinkedConnectProfile
	endpoint := fmt.Sprintf("%s/jamf-connect/config-profiles/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateJamfConnectConfigProfileV1(%s): %w", id, err)
	}
	return &result, nil
}

// ListJamfConnectDeploymentTasksV1 search for deployment tasks for a config profile linked to Jamf Connect.
func (c *Client) ListJamfConnectDeploymentTasksV1(ctx context.Context, id string, sort []string, filter string) ([]DeploymentTask, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]DeploymentTask, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/jamf-connect/deployments/%s/tasks", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int              `json:"totalCount"`
			Results    []DeploymentTask `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// RetryJamfConnectDeploymentTasksV1 request a retry of Connect install tasks.
func (c *Client) RetryJamfConnectDeploymentTasksV1(ctx context.Context, id string, request *Ids) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/jamf-connect/deployments/%s/tasks/retry", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("RetryJamfConnectDeploymentTasksV1(%s): %w", id, err)
	}
	return nil
}

// ListJamfConnectHistoryV1 get Jamf Connect history.
func (c *Client) ListJamfConnectHistoryV1(ctx context.Context, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/jamf-connect/history"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateJamfConnectHistoryNoteV1 add Jamf Connect history notes.
func (c *Client) CreateJamfConnectHistoryNoteV1(ctx context.Context, request *ObjectHistoryNote) (*HrefResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result HrefResponse
	endpoint := prefix + "/jamf-connect/history"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateJamfConnectHistoryNoteV1: %w", err)
	}
	return &result, nil
}
