// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
)

// InitializeSystemV1 set up fresh installed Jamf Pro Server.
func (c *Client) InitializeSystemV1(ctx context.Context, request *InitializeV1) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := prefix + "/system/initialize"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusAccepted, nil); err != nil {
		return fmt.Errorf("InitializeSystemV1: %w", err)
	}
	return nil
}

// PlatformInitializeSystemV1 set up fresh installed Jamf Pro Server for Platform.
func (c *Client) PlatformInitializeSystemV1(ctx context.Context, request *PlatformInitializeV1) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := prefix + "/system/platform-initialize"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusAccepted, nil); err != nil {
		return fmt.Errorf("PlatformInitializeSystemV1: %w", err)
	}
	return nil
}
