// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
)

// GetLastLoginV1 get the date of the last login event.
func (c *Client) GetLastLoginV1(ctx context.Context) (*LastLoginResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result LastLoginResponse
	endpoint := prefix + "/last-login"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetLastLoginV1: %w", err)
	}
	return &result, nil
}
