// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
)

// ListLocalesV1 return locales that can be used in other features.
//
// Required privileges: none (callable by any authenticated API client).
func (c *Client) ListLocalesV1(ctx context.Context) ([]Locale, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result []Locale
	endpoint := prefix + "/locales"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListLocalesV1: %w", err)
	}
	return result, nil
}
