// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetLAPSPendingRotationsV2 get a list of the current devices and usernames with pending LAPS rotations.
func (c *Client) GetLAPSPendingRotationsV2(ctx context.Context) (*LapsPendingRotationResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsPendingRotationResponse
	endpoint := prefix + "/local-admin-password/pending-rotations"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetLAPSPendingRotationsV2: %w", err)
	}
	return &result, nil
}

// GetLAPSSettingsV2 get the current LAPS settings.
func (c *Client) GetLAPSSettingsV2(ctx context.Context) (*LapsSettingsResponseV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsSettingsResponseV2
	endpoint := prefix + "/local-admin-password/settings"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetLAPSSettingsV2: %w", err)
	}
	return &result, nil
}

// UpdateLAPSSettingsV2 update settings for LAPS.
func (c *Client) UpdateLAPSSettingsV2(ctx context.Context, request *LapsSettingsRequestV2) (*LapsSettingsResponseV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsSettingsResponseV2
	endpoint := prefix + "/local-admin-password/settings"
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateLAPSSettingsV2: %w", err)
	}
	return &result, nil
}

// ListLAPSAccountsV2 get the LAPS capable admin accounts for a device.
func (c *Client) ListLAPSAccountsV2(ctx context.Context, clientManagementID string) (*LapsUserResultsV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsUserResultsV2
	endpoint := fmt.Sprintf("%s/local-admin-password/%s/accounts", prefix, url.PathEscape(clientManagementID))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListLAPSAccountsV2(%s): %w", clientManagementID, err)
	}
	return &result, nil
}

// ListLAPSHistoryV2 get LAPS password viewed history, and rotation history.
func (c *Client) ListLAPSHistoryV2(ctx context.Context, clientManagementID string) (*LapsAccountManagementHistoryResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsAccountManagementHistoryResponse
	endpoint := fmt.Sprintf("%s/local-admin-password/%s/history", prefix, url.PathEscape(clientManagementID))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListLAPSHistoryV2(%s): %w", clientManagementID, err)
	}
	return &result, nil
}

// GetLAPSAccountAuditV2 get LAPS password viewed history.
func (c *Client) GetLAPSAccountAuditV2(ctx context.Context, clientManagementID string, username string) (*LapsPasswordAuditsResultsV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsPasswordAuditsResultsV2
	endpoint := fmt.Sprintf("%s/local-admin-password/%s/account/%s/audit", prefix, url.PathEscape(clientManagementID), url.PathEscape(username))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetLAPSAccountAuditV2(%s): %w", clientManagementID, err)
	}
	return &result, nil
}

// GetLAPSAccountHistoryV2 get LAPS historical records for target device and username.
func (c *Client) GetLAPSAccountHistoryV2(ctx context.Context, clientManagementID string, username string) (*LapsHistoryResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsHistoryResponse
	endpoint := fmt.Sprintf("%s/local-admin-password/%s/account/%s/history", prefix, url.PathEscape(clientManagementID), url.PathEscape(username))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetLAPSAccountHistoryV2(%s): %w", clientManagementID, err)
	}
	return &result, nil
}

// GetLAPSAccountPasswordV2 get current LAPS password for specified username on a client.
func (c *Client) GetLAPSAccountPasswordV2(ctx context.Context, clientManagementID string, username string) (*LapsPasswordResponseV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsPasswordResponseV2
	endpoint := fmt.Sprintf("%s/local-admin-password/%s/account/%s/password", prefix, url.PathEscape(clientManagementID), url.PathEscape(username))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetLAPSAccountPasswordV2(%s): %w", clientManagementID, err)
	}
	return &result, nil
}

// GetLAPSAccountGuidAuditV2 get LAPS password viewed history.
func (c *Client) GetLAPSAccountGuidAuditV2(ctx context.Context, clientManagementID string, username string, guid string) (*LapsPasswordAuditsResultsV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsPasswordAuditsResultsV2
	endpoint := fmt.Sprintf("%s/local-admin-password/%s/account/%s/%s/audit", prefix, url.PathEscape(clientManagementID), url.PathEscape(username), url.PathEscape(guid))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetLAPSAccountGuidAuditV2(%s): %w", clientManagementID, err)
	}
	return &result, nil
}

// GetLAPSAccountGuidHistoryV2 get LAPS historical records for target device and user guid.
func (c *Client) GetLAPSAccountGuidHistoryV2(ctx context.Context, clientManagementID string, username string, guid string) (*LapsHistoryResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsHistoryResponse
	endpoint := fmt.Sprintf("%s/local-admin-password/%s/account/%s/%s/history", prefix, url.PathEscape(clientManagementID), url.PathEscape(username), url.PathEscape(guid))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetLAPSAccountGuidHistoryV2(%s): %w", clientManagementID, err)
	}
	return &result, nil
}

// GetLAPSAccountGuidPasswordV2 get current LAPS password for specified user guid on a client.
func (c *Client) GetLAPSAccountGuidPasswordV2(ctx context.Context, clientManagementID string, username string, guid string) (*LapsPasswordResponseV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsPasswordResponseV2
	endpoint := fmt.Sprintf("%s/local-admin-password/%s/account/%s/%s/password", prefix, url.PathEscape(clientManagementID), url.PathEscape(username), url.PathEscape(guid))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetLAPSAccountGuidPasswordV2(%s): %w", clientManagementID, err)
	}
	return &result, nil
}

// SetLAPSPasswordV2 set the LAPS password for a device.
func (c *Client) SetLAPSPasswordV2(ctx context.Context, clientManagementID string, request *LapsUserPasswordRequestV2) (*LapsUserPasswordResponseV2, error) {
	prefix := c.transport.TenantPrefix("pro", "v2")
	var result LapsUserPasswordResponseV2
	endpoint := fmt.Sprintf("%s/local-admin-password/%s/set-password", prefix, url.PathEscape(clientManagementID))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("SetLAPSPasswordV2(%s): %w", clientManagementID, err)
	}
	return &result, nil
}
