// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"net/http"
	"testing"
)

func TestListMobileDeviceExtensionAttributesV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{
			"results":    []map[string]any{{}},
			"totalCount": 1,
			"hasNext":    false,
		})
	})

	results, err := c.ListMobileDeviceExtensionAttributesV1(context.Background(), nil, "")
	if err != nil {
		t.Fatal(err)
	}
	if len(results) != 1 {
		t.Fatalf("len = %d, want 1", len(results))
	}
}

func TestCreateMobileDeviceExtensionAttributeV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		writeJSON(t, w, http.StatusCreated, map[string]any{})
	})

	result, err := c.CreateMobileDeviceExtensionAttributeV1(context.Background(), &MobileDeviceExtensionAttributes{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetMobileDeviceExtensionAttributeV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{})
	})

	result, err := c.GetMobileDeviceExtensionAttributeV1(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetMobileDeviceExtensionAttributeV1_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(t, w, http.StatusNotFound, map[string]any{
			"httpStatus": 404,
			"traceId":    "trace-nf",
			"errors":     []map[string]string{{"code": "NOT_FOUND", "field": "id", "description": "not found"}},
		})
	})

	_, err := c.GetMobileDeviceExtensionAttributeV1(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestUpdateMobileDeviceExtensionAttributeV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPut {
			t.Errorf("method = %s, want PUT", r.Method)
		}
		writeJSON(t, w, http.StatusAccepted, map[string]any{})
	})

	result, err := c.UpdateMobileDeviceExtensionAttributeV1(context.Background(), "test-id", &MobileDeviceExtensionAttributes{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestDeleteMobileDeviceExtensionAttributeV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(http.StatusNoContent)
	})

	err := c.DeleteMobileDeviceExtensionAttributeV1(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
}

func TestGetMobileDeviceExtensionAttributeDataDependencyV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes/test-id/data-dependency", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{})
	})

	result, err := c.GetMobileDeviceExtensionAttributeDataDependencyV1(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetMobileDeviceExtensionAttributeDataDependencyV1_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes/test-id/data-dependency", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(t, w, http.StatusNotFound, map[string]any{
			"httpStatus": 404,
			"traceId":    "trace-nf",
			"errors":     []map[string]string{{"code": "NOT_FOUND", "field": "id", "description": "not found"}},
		})
	})

	_, err := c.GetMobileDeviceExtensionAttributeDataDependencyV1(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestListMobileDeviceExtensionAttributeHistoryV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes/test-id/history", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{
			"results":    []map[string]any{{}},
			"totalCount": 1,
			"hasNext":    false,
		})
	})

	results, err := c.ListMobileDeviceExtensionAttributeHistoryV1(context.Background(), "test-id", nil, "")
	if err != nil {
		t.Fatal(err)
	}
	if len(results) != 1 {
		t.Fatalf("len = %d, want 1", len(results))
	}
}

func TestCreateMobileDeviceExtensionAttributeHistoryNoteV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes/test-id/history", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		writeJSON(t, w, http.StatusCreated, map[string]any{})
	})

	result, err := c.CreateMobileDeviceExtensionAttributeHistoryNoteV1(context.Background(), "test-id", &ObjectHistoryNote{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestListDeviceExtensionAttributesPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/tenant/t-test/devices/extensionAttributes", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{})
	})

	result, err := c.ListDeviceExtensionAttributesPreview(context.Background(), "")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestListDeviceExtensionAttributesPreview_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/tenant/t-test/devices/extensionAttributes", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(t, w, http.StatusNotFound, map[string]any{
			"httpStatus": 404,
			"traceId":    "trace-nf",
			"errors":     []map[string]string{{"code": "NOT_FOUND", "field": "id", "description": "not found"}},
		})
	})

	_, err := c.ListDeviceExtensionAttributesPreview(context.Background(), "")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestResolveMobileDeviceExtensionAttributeV1IDByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{
			"results": []map[string]any{
				{"id": "resolved-id", "name": "target"},
			},
			"totalCount": 1,
		})
	})

	id, err := c.ResolveMobileDeviceExtensionAttributeV1IDByName(context.Background(), "target")
	if err != nil {
		t.Fatal(err)
	}
	if id != "resolved-id" {
		t.Errorf("id = %q, want resolved-id", id)
	}
}

func TestResolveMobileDeviceExtensionAttributeV1ByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/mobile-device-extension-attributes", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{
			"results": []map[string]any{
				{"id": "resolved-id", "name": "target"},
			},
			"totalCount": 1,
		})
	})

	result, err := c.ResolveMobileDeviceExtensionAttributeV1ByName(context.Background(), "target")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}
