// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// GetParentAppSettingsV1 get the current Jamf Parent app settings.
func (c *Client) GetParentAppSettingsV1(ctx context.Context) (*ParentApp, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result ParentApp
	endpoint := prefix + "/parent-app"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetParentAppSettingsV1: %w", err)
	}
	return &result, nil
}

// UpdateParentAppSettingsV1 update Jamf Parent app settings.
func (c *Client) UpdateParentAppSettingsV1(ctx context.Context, request *ParentApp) (*ParentApp, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result ParentApp
	endpoint := prefix + "/parent-app"
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateParentAppSettingsV1: %w", err)
	}
	return &result, nil
}

// ListParentAppHistoryV1 get Jamf Parent app settings history.
func (c *Client) ListParentAppHistoryV1(ctx context.Context, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/parent-app/history"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateParentAppHistoryNoteV1 add Jamf Parent app settings history notes.
func (c *Client) CreateParentAppHistoryNoteV1(ctx context.Context, request *ObjectHistoryNote) (*ObjectHistory, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result ObjectHistory
	endpoint := prefix + "/parent-app/history"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateParentAppHistoryNoteV1: %w", err)
	}
	return &result, nil
}
