// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ListIOSBrandingConfigurationsV1 search for sorted and paged iOS branding configurations.
func (c *Client) ListIOSBrandingConfigurationsV1(ctx context.Context, sort []string) ([]IosBrandingConfiguration, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]IosBrandingConfiguration, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}

		endpoint := prefix + "/self-service/branding/ios"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                        `json:"totalCount"`
			Results    []IosBrandingConfiguration `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateIOSBrandingConfigurationV1 create a Self Service iOS branding configuration with the supplied.
func (c *Client) CreateIOSBrandingConfigurationV1(ctx context.Context, request *IosBrandingConfiguration) (*HrefResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result HrefResponse
	endpoint := prefix + "/self-service/branding/ios"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateIOSBrandingConfigurationV1: %w", err)
	}
	return &result, nil
}

// GetIOSBrandingConfigurationV1 read a single Self Service iOS branding configuration indicated by the provided id.
func (c *Client) GetIOSBrandingConfigurationV1(ctx context.Context, id string) (*IosBrandingConfiguration, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result IosBrandingConfiguration
	endpoint := fmt.Sprintf("%s/self-service/branding/ios/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetIOSBrandingConfigurationV1(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateIOSBrandingConfigurationV1 update a Self Service iOS branding configuration with the supplied details.
func (c *Client) UpdateIOSBrandingConfigurationV1(ctx context.Context, id string, request *IosBrandingConfiguration) (*IosBrandingConfiguration, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result IosBrandingConfiguration
	endpoint := fmt.Sprintf("%s/self-service/branding/ios/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateIOSBrandingConfigurationV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteIOSBrandingConfigurationV1 delete the Self Service iOS branding configuration indicated by the provided id.
func (c *Client) DeleteIOSBrandingConfigurationV1(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/self-service/branding/ios/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteIOSBrandingConfigurationV1(%s): %w", id, err)
	}
	return nil
}
