// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"bytes"
	"context"
	"net/http"
	"strings"
	"testing"
)

func TestUploadBrandingImageV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/tenant/t-test/self-service/branding/images", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		if ct := r.Header.Get("Content-Type"); !strings.HasPrefix(ct, "multipart/form-data") {
			t.Errorf("Content-Type = %q, want multipart/form-data", ct)
		}
		writeJSON(t, w, http.StatusCreated, map[string]any{})
	})
	result, err := c.UploadBrandingImageV1(context.Background(), "test.bin", bytes.NewBufferString("stub"))
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}
