// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ListSitesV1 find all sites.
func (c *Client) ListSitesV1(ctx context.Context) ([]V1Site, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result []V1Site
	endpoint := prefix + "/sites"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListSitesV1: %w", err)
	}
	return result, nil
}

// ListSiteObjectsV1 find and filter site objects for a site ID.
func (c *Client) ListSiteObjectsV1(ctx context.Context, id string, sort []string, filter string) ([]SiteObject, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]SiteObject, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/sites/%s/objects", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result []SiteObject
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		return result, len(result) >= pageSize && len(result) > 0, nil
	})
}

// ResolveSiteV1IDByName looks up a SiteV1 by its name field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveSiteV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	listPath := prefix + "/sites"
	id, _, err := c.transport.ResolveByNameClient(ctx, listPath, "", "", "name", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveSiteV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveSiteV1ByName looks up a SiteV1 by its name field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveSiteV1ByName(ctx context.Context, name string) (*V1Site, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	listPath := prefix + "/sites"
	_, raw, err := c.transport.ResolveByNameClient(ctx, listPath, "", "", "name", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveSiteV1ByName(%s): %w", name, err)
	}
	var out V1Site
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveSiteV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}
