// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
)

// GetSlasaAcceptanceV1 get the status of SLASA.
func (c *Client) GetSlasaAcceptanceV1(ctx context.Context) (*SlasaAcceptance, error) {
	prefix := c.transport.TenantPrefix("pro", "v1")
	var result SlasaAcceptance
	endpoint := prefix + "/slasa"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetSlasaAcceptanceV1: %w", err)
	}
	return &result, nil
}

// AcceptSlasaV1 accept the SLASA.
func (c *Client) AcceptSlasaV1(ctx context.Context) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := prefix + "/slasa"
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("AcceptSlasaV1: %w", err)
	}
	return nil
}
