// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// GetSsoSettingsV3 retrieve the current Single Sign On configuration settings.
func (c *Client) GetSsoSettingsV3(ctx context.Context) (*SsoSettingsV3, error) {
	prefix := c.transport.TenantPrefix("pro", "v3")
	var result SsoSettingsV3
	endpoint := prefix + "/sso"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetSsoSettingsV3: %w", err)
	}
	return &result, nil
}

// UpdateSsoSettingsV3 updates the current Single Sign On configuration settings.
func (c *Client) UpdateSsoSettingsV3(ctx context.Context, request *SsoSettingsV3) (*SsoSettingsV3, error) {
	prefix := c.transport.TenantPrefix("pro", "v3")
	var result SsoSettingsV3
	endpoint := prefix + "/sso"
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateSsoSettingsV3: %w", err)
	}
	return &result, nil
}

// GetSsoDependenciesV3 retrieve the list of Enrollment Customizations using SSO.
func (c *Client) GetSsoDependenciesV3(ctx context.Context) (*EnrollmentCustomizationDependencies, error) {
	prefix := c.transport.TenantPrefix("pro", "v3")
	var result EnrollmentCustomizationDependencies
	endpoint := prefix + "/sso/dependencies"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetSsoDependenciesV3: %w", err)
	}
	return &result, nil
}

// DisableSsoV3 disable SSO.
func (c *Client) DisableSsoV3(ctx context.Context) error {
	prefix := c.transport.TenantPrefix("pro", "v3")
	endpoint := prefix + "/sso/disable"
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusAccepted, nil); err != nil {
		return fmt.Errorf("DisableSsoV3: %w", err)
	}
	return nil
}

// ListSsoHistoryV3 get SSO history object.
func (c *Client) ListSsoHistoryV3(ctx context.Context, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.TenantPrefix("pro", "v3")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/sso/history"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateSsoHistoryNoteV3 add SSO history object notes.
func (c *Client) CreateSsoHistoryNoteV3(ctx context.Context, request *ObjectHistoryNote) (*HrefResponse, error) {
	prefix := c.transport.TenantPrefix("pro", "v3")
	var result HrefResponse
	endpoint := prefix + "/sso/history"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateSsoHistoryNoteV3: %w", err)
	}
	return &result, nil
}

// DownloadSsoMetadataV3 download the Jamf Pro SAML metadata file.
func (c *Client) DownloadSsoMetadataV3(ctx context.Context) ([]byte, error) {
	prefix := c.transport.TenantPrefix("pro", "v3")
	var result []byte
	endpoint := prefix + "/sso/metadata/download"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("DownloadSsoMetadataV3: %w", err)
	}
	return result, nil
}
