// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
)

// GetSsoFailoverV1 retrieve the current failover settings.
//
// Required privileges: sso-settings:read. Legacy Jamf Pro privilege name(s): Read SSO Settings.
func (c *Client) GetSsoFailoverV1(ctx context.Context) (*SsoFailoverData, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result SsoFailoverData
	endpoint := prefix + "/sso/failover"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetSsoFailoverV1: %w", err)
	}
	return &result, nil
}

// GenerateSsoFailoverV1 regenerates failover url.
//
// Required privileges: sso-settings:update. Legacy Jamf Pro privilege name(s): Update SSO Settings.
func (c *Client) GenerateSsoFailoverV1(ctx context.Context) (*SsoFailoverData, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result SsoFailoverData
	endpoint := prefix + "/sso/failover/generate"
	if err := c.transport.Do(ctx, http.MethodPost, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GenerateSsoFailoverV1: %w", err)
	}
	return &result, nil
}
