// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"net/http"
	"testing"
)

func TestCreateTeamViewerConfigurationPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		writeJSON(t, w, http.StatusCreated, map[string]any{})
	})

	result, err := c.CreateTeamViewerConfigurationPreview(context.Background(), &ConnectionConfigurationCandidateRequest{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetTeamViewerConfigurationPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{})
	})

	result, err := c.GetTeamViewerConfigurationPreview(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetTeamViewerConfigurationPreview_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(t, w, http.StatusNotFound, map[string]any{
			"httpStatus": 404,
			"traceId":    "trace-nf",
			"errors":     []map[string]string{{"code": "NOT_FOUND", "field": "id", "description": "not found"}},
		})
	})

	_, err := c.GetTeamViewerConfigurationPreview(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestUpdateTeamViewerConfigurationPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPatch {
			t.Errorf("method = %s, want PATCH", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{})
	})

	result, err := c.UpdateTeamViewerConfigurationPreview(context.Background(), "test-id", &ConnectionConfigurationUpdateRequest{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestDeleteTeamViewerConfigurationPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(http.StatusNoContent)
	})

	err := c.DeleteTeamViewerConfigurationPreview(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
}

func TestGetTeamViewerConfigurationStatusPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id/status", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{})
	})

	result, err := c.GetTeamViewerConfigurationStatusPreview(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetTeamViewerConfigurationStatusPreview_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id/status", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(t, w, http.StatusNotFound, map[string]any{
			"httpStatus": 404,
			"traceId":    "trace-nf",
			"errors":     []map[string]string{{"code": "NOT_FOUND", "field": "id", "description": "not found"}},
		})
	})

	_, err := c.GetTeamViewerConfigurationStatusPreview(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestListTeamViewerSessionsPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id/sessions", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{
			"results":    []map[string]any{{}},
			"totalCount": 1,
			"hasNext":    false,
		})
	})

	results, err := c.ListTeamViewerSessionsPreview(context.Background(), "test-id", "")
	if err != nil {
		t.Fatal(err)
	}
	if len(results) != 1 {
		t.Fatalf("len = %d, want 1", len(results))
	}
}

func TestCreateTeamViewerSessionPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id/sessions", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		writeJSON(t, w, http.StatusCreated, map[string]any{})
	})

	result, err := c.CreateTeamViewerSessionPreview(context.Background(), "test-id", &SessionCandidateRequest{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetTeamViewerSessionPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id/sessions/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{})
	})

	result, err := c.GetTeamViewerSessionPreview(context.Background(), "test-id", "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetTeamViewerSessionPreview_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id/sessions/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(t, w, http.StatusNotFound, map[string]any{
			"httpStatus": 404,
			"traceId":    "trace-nf",
			"errors":     []map[string]string{{"code": "NOT_FOUND", "field": "id", "description": "not found"}},
		})
	})

	_, err := c.GetTeamViewerSessionPreview(context.Background(), "test-id", "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestGetTeamViewerSessionStatusPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id/sessions/test-id/status", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{})
	})

	result, err := c.GetTeamViewerSessionStatusPreview(context.Background(), "test-id", "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetTeamViewerSessionStatusPreview_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id/sessions/test-id/status", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(t, w, http.StatusNotFound, map[string]any{
			"httpStatus": 404,
			"traceId":    "trace-nf",
			"errors":     []map[string]string{{"code": "NOT_FOUND", "field": "id", "description": "not found"}},
		})
	})

	_, err := c.GetTeamViewerSessionStatusPreview(context.Background(), "test-id", "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestCloseTeamViewerSessionPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id/sessions/test-id/close", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusNoContent)
	})

	err := c.CloseTeamViewerSessionPreview(context.Background(), "test-id", "test-id")
	if err != nil {
		t.Fatal(err)
	}
}

func TestResendTeamViewerSessionNotificationPreview(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/pro/preview/remote-administration-configurations/team-viewer/test-id/sessions/test-id/resend-notification", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusNoContent)
	})

	err := c.ResendTeamViewerSessionNotificationPreview(context.Background(), "test-id", "test-id")
	if err != nil {
		t.Fatal(err)
	}
}
