// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
)

// ListTimeZonesV1 return information about the currently supported Time Zones.
//
// Required privileges: none (callable by any authenticated API client).
func (c *Client) ListTimeZonesV1(ctx context.Context) ([]TimeZone, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result []TimeZone
	endpoint := prefix + "/time-zones"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListTimeZonesV1: %w", err)
	}
	return result, nil
}
