// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
)

// IssueTomcatSslCertificate generate a SSL Certificate using Jamf Certificate Authority.
//
// Required privileges: update:pro:apache-tomcat-settings. Legacy Jamf Pro privilege name(s): Update Apache Tomcat Settings.
func (c *Client) IssueTomcatSslCertificate(ctx context.Context) error {
	prefix := c.transport.APIPrefix("pro", "")
	endpoint := prefix + "/settings/issueTomcatSslCertificate"
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("IssueTomcatSslCertificate: %w", err)
	}
	return nil
}
