// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

// ApiError represents a api error.
type ApiError struct {
	Errors     []ApiErrorCause `json:"errors"`
	HttpStatus int             `json:"httpStatus"`
}

// ApiErrorCause represents a api error cause.
type ApiErrorCause struct {
	Code        string  `json:"code"`
	Description string  `json:"description"`
	Field       string  `json:"field"`
	ID          *string `json:"id,omitempty"`
}

// Building represents a building.
type Building struct {
	City           *string `json:"city,omitempty"`
	Country        *string `json:"country,omitempty"`
	ID             *string `json:"id,omitempty"`
	Name           string  `json:"name"`
	StateProvince  *string `json:"stateProvince,omitempty"`
	StreetAddress1 *string `json:"streetAddress1,omitempty"`
	StreetAddress2 *string `json:"streetAddress2,omitempty"`
	ZipPostalCode  *string `json:"zipPostalCode,omitempty"`
}

// BuildingSearchResults represents a building search results.
type BuildingSearchResults struct {
	Results    []Building `json:"results"`
	TotalCount int        `json:"totalCount"`
}

// HrefResponse represents a href response.
type HrefResponse struct {
	Href string `json:"href"`
	ID   string `json:"id"`
}

// StartupStatus represents a startup status.
type StartupStatus struct {
	Error                   *string `json:"error,omitempty"`
	ErrorCode               *string `json:"errorCode,omitempty"`
	Percentage              int     `json:"percentage"`
	SetupAssistantNecessary bool    `json:"setupAssistantNecessary"`
	Step                    string  `json:"step"`
	StepCode                string  `json:"stepCode"`
	StepParam               *string `json:"stepParam,omitempty"`
	Warning                 *string `json:"warning,omitempty"`
	WarningCode             *string `json:"warningCode,omitempty"`
	WarningParam            *string `json:"warningParam,omitempty"`
}

// ---------------------------------------------------------------------------
// Methods
// ---------------------------------------------------------------------------
