// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
)

// GetUserSessionV1 return all Jamf Pro user acounts.
func (c *Client) GetUserSessionV1(ctx context.Context) ([]Account, error) {
	prefix := c.transport.TenantPrefix("pro", "")
	var result []Account
	endpoint := prefix + "/user"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetUserSessionV1: %w", err)
	}
	return result, nil
}

// UpdateUserSessionV1 update values in the User's current session.
func (c *Client) UpdateUserSessionV1(ctx context.Context, request *Session) (*Session, error) {
	prefix := c.transport.TenantPrefix("pro", "")
	var result Session
	endpoint := prefix + "/user/updateSession"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateUserSessionV1: %w", err)
	}
	return &result, nil
}
