// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"net/http"
	"testing"
)

func TestChangeUserPasswordV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/pro/v1/tenant/t-test/user/change-password", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusAccepted)
	})

	err := c.ChangeUserPasswordV1(context.Background(), &ChangePassword{})
	if err != nil {
		t.Fatal(err)
	}
}
