// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
)

// ChangeUserPasswordV1 changes the user account password.
//
// This endpoint is rate-limited. The transport retries a 429 response once if the server returns a bounded Retry-After; otherwise the 429 surfaces as an APIResponseError so the caller can apply its own backoff policy.
func (c *Client) ChangeUserPasswordV1(ctx context.Context, request *ChangePassword) error {
	prefix := c.transport.TenantPrefix("pro", "v1")
	endpoint := prefix + "/user/change-password"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusAccepted, nil); err != nil {
		return fmt.Errorf("ChangeUserPasswordV1: %w", err)
	}
	return nil
}
