// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"encoding/json"
	"fmt"
	"reflect"
)

// zeroVersionLock recursively walks v (must be a pointer to a struct)
// and sets every field named "VersionLock" of type int to 0. This
// satisfies the Jamf API requirement that all versionLock fields be
// zero on resource creation.
func zeroVersionLock(v any) {
	rv := reflect.ValueOf(v)
	if rv.Kind() == reflect.Ptr {
		rv = rv.Elem()
	}
	if rv.Kind() != reflect.Struct {
		return
	}
	rt := rv.Type()
	for i := 0; i < rv.NumField(); i++ {
		f := rv.Field(i)
		ft := rt.Field(i)
		if ft.Name == "VersionLock" && f.Kind() == reflect.Int && f.CanSet() {
			f.SetInt(0)
			continue
		}
		switch f.Kind() {
		case reflect.Struct:
			zeroVersionLock(f.Addr().Interface())
		case reflect.Ptr:
			if !f.IsNil() && f.Elem().Kind() == reflect.Struct {
				zeroVersionLock(f.Interface())
			}
		}
	}
}

// convertAndInjectVersionLock converts a create request (src) to update
// type U via JSON round-trip, then injects all VersionLock field values
// from the current GET response (current) into the resulting update request.
// This implements the optimistic locking requirement: the update request
// must carry the current versionLock values so the server can detect
// concurrent modifications.
func convertAndInjectVersionLock[U any, G any](src any, current *G) (*U, error) {
	data, err := json.Marshal(src)
	if err != nil {
		return nil, fmt.Errorf("marshal for update: %w", err)
	}
	var updateReq U
	if err := json.Unmarshal(data, &updateReq); err != nil {
		return nil, fmt.Errorf("unmarshal for update: %w", err)
	}
	injectVersionLock(reflect.ValueOf(&updateReq).Elem(), reflect.ValueOf(current).Elem())
	return &updateReq, nil
}

// injectVersionLock recursively copies VersionLock field values from src
// into dst. Both must be struct values. Fields are matched by name; if a
// VersionLock field exists in both, the src value is copied to dst.
func injectVersionLock(dst, src reflect.Value) {
	if dst.Kind() == reflect.Ptr {
		if dst.IsNil() {
			return
		}
		dst = dst.Elem()
	}
	if src.Kind() == reflect.Ptr {
		if src.IsNil() {
			return
		}
		src = src.Elem()
	}
	if dst.Kind() != reflect.Struct || src.Kind() != reflect.Struct {
		return
	}
	dstType := dst.Type()
	for i := 0; i < dst.NumField(); i++ {
		df := dst.Field(i)
		dft := dstType.Field(i)
		if dft.Name == "VersionLock" && df.Kind() == reflect.Int && df.CanSet() {
			sf := src.FieldByName("VersionLock")
			if sf.IsValid() && sf.Kind() == reflect.Int {
				df.SetInt(sf.Int())
			}
			continue
		}
		sf := src.FieldByName(dft.Name)
		if !sf.IsValid() {
			continue
		}
		switch df.Kind() {
		case reflect.Struct:
			injectVersionLock(df, sf)
		case reflect.Ptr:
			if !df.IsNil() {
				injectVersionLock(df, sf)
			}
		}
	}
}
