// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package devicegroups

import "github.com/Jamf-Concepts/jamfplatform-go-sdk/jamfplatform"

// Privileges maps each devicegroups SDK method name to the Jamf API privileges it
// requires, sourced from the x-required-privileges vendor extensions in the
// Jamf OpenAPI specs. Identifiers are GA capability permissions in
// {capability}:{action} form and a multi-entry Scoped slice means all of them
// are required. An empty Scoped slice means the spec declares none — see
// jamfplatform.MethodPrivileges for why that is not the same as none being
// required. Synthetic Resolve<X>ByName / Apply<X> methods are not present;
// document the privileges of the operations they call instead.
var Privileges = map[string]jamfplatform.MethodPrivileges{
	"CreateDeviceGroup":         {Method: "CreateDeviceGroup", HTTPMethod: "POST", Path: "/v1/device-groups", Scoped: []string{"device-groups:create"}, Legacy: nil},
	"DeleteDeviceGroup":         {Method: "DeleteDeviceGroup", HTTPMethod: "DELETE", Path: "/v1/device-groups/{id}", Scoped: []string{"device-groups:delete"}, Legacy: nil},
	"GetDeviceGroup":            {Method: "GetDeviceGroup", HTTPMethod: "GET", Path: "/v1/device-groups/{id}", Scoped: []string{"device-groups:read"}, Legacy: nil},
	"ListDeviceGroupMembers":    {Method: "ListDeviceGroupMembers", HTTPMethod: "GET", Path: "/v1/device-groups/{id}/members", Scoped: []string{"device-groups:read"}, Legacy: nil},
	"ListDeviceGroups":          {Method: "ListDeviceGroups", HTTPMethod: "GET", Path: "/v1/device-groups", Scoped: []string{"device-groups:read"}, Legacy: nil},
	"ListDeviceGroupsForDevice": {Method: "ListDeviceGroupsForDevice", HTTPMethod: "GET", Path: "/v1/devices/{id}/device-groups", Scoped: []string{"device-groups:read"}, Legacy: nil},
	"UpdateDeviceGroup":         {Method: "UpdateDeviceGroup", HTTPMethod: "PATCH", Path: "/v1/device-groups/{id}", Scoped: []string{"device-groups:update"}, Legacy: nil},
	"UpdateDeviceGroupMembers":  {Method: "UpdateDeviceGroupMembers", HTTPMethod: "PATCH", Path: "/v1/device-groups/{id}/members", Scoped: []string{"device-groups:update"}, Legacy: nil},
}

// PrivilegesFor returns the privilege metadata for the named SDK method and
// true when the method is present in the registry, or the zero value and
// false otherwise.
func PrivilegesFor(method string) (jamfplatform.MethodPrivileges, bool) {
	p, ok := Privileges[method]
	return p, ok
}
