// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package audit

import "github.com/Jamf-Concepts/jamfplatform-go-sdk/jamfplatform"

// Privileges maps each audit SDK method name to the Jamf API privileges it
// requires, sourced from the x-required-privileges vendor extensions in the
// Jamf OpenAPI specs. Methods that require no special privilege have an empty
// Scoped slice. Synthetic Resolve<X>ByName / Apply<X> methods are not present;
// document the privileges of the operations they call instead.
var Privileges = map[string]jamfplatform.MethodPrivileges{
	"GetResourceLineage":     {Method: "GetResourceLineage", HTTPMethod: "GET", Path: "/v1/audit/resources/{resourceId}/lineage", Scoped: []string{"audit:read"}, Legacy: nil},
	"GetTransactionTimeline": {Method: "GetTransactionTimeline", HTTPMethod: "GET", Path: "/v1/audit/transactions/{txId}", Scoped: []string{"audit:read"}, Legacy: nil},
	"ListAuditEvents":        {Method: "ListAuditEvents", HTTPMethod: "GET", Path: "/v1/audit", Scoped: []string{"audit:read"}, Legacy: nil},
	"ListAuditSources":       {Method: "ListAuditSources", HTTPMethod: "GET", Path: "/v1/audit/sources", Scoped: []string{"audit:read"}, Legacy: nil},
}

// PrivilegesFor returns the privilege metadata for the named SDK method and
// true when the method is present in the registry, or the zero value and
// false otherwise.
func PrivilegesFor(method string) (jamfplatform.MethodPrivileges, bool) {
	p, ok := Privileges[method]
	return p, ok
}
