// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"encoding/xml"
	"strings"
	"testing"
)

// TestGroupPrivileges_RoundTrip_MarshalXMLCategory verifies that a
// MarshalXML-bearing category (casper_admin) emits ONE container element
// with N <privilege> children — not N repeated container elements. Mirrors
// the class-fix regression guard.
func TestGroupPrivileges_RoundTrip_MarshalXMLCategory(t *testing.T) {
	privs := []string{"Read Computers", "Update Computers", "Create Computers"}
	g := Group{
		Privileges: &GroupPrivileges{
			CasperAdmin: &GroupPrivilegesCasperAdmin{Privilege: &privs},
		},
	}
	out, err := xml.Marshal(g)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got := string(out)
	if n := strings.Count(got, "<casper_admin>"); n != 1 {
		t.Fatalf("want 1 <casper_admin> wrapper, got %d:\n%s", n, got)
	}
	if n := strings.Count(got, "<privilege>"); n != 3 {
		t.Fatalf("want 3 <privilege> children, got %d:\n%s", n, got)
	}

	var back Group
	if err := xml.Unmarshal(out, &back); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if back.Privileges == nil || back.Privileges.CasperAdmin == nil || back.Privileges.CasperAdmin.Privilege == nil {
		t.Fatal("privileges.casper_admin decoded as nil")
	}
	got2 := *back.Privileges.CasperAdmin.Privilege
	if len(got2) != 3 {
		t.Fatalf("want 3 privileges after unmarshal, got %d: %v", len(got2), got2)
	}
	for i, want := range privs {
		if got2[i] != want {
			t.Fatalf("privilege[%d]: want %q, got %q", i, want, got2[i])
		}
	}
}

// TestGroupPrivileges_RoundTrip_PlainCategory verifies that a plain category
// (jss_objects, no custom MarshalXML on the item type) also emits ONE
// container with N children.
func TestGroupPrivileges_RoundTrip_PlainCategory(t *testing.T) {
	privs := []string{"Create Computers", "Read Computers", "Update Computers"}
	g := Group{
		Privileges: &GroupPrivileges{
			JssObjects: &GroupPrivilegesJssObjects{Privilege: &privs},
		},
	}
	out, err := xml.Marshal(g)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got := string(out)
	if n := strings.Count(got, "<jss_objects>"); n != 1 {
		t.Fatalf("want 1 <jss_objects> wrapper, got %d:\n%s", n, got)
	}
	if n := strings.Count(got, "<privilege>"); n != 3 {
		t.Fatalf("want 3 <privilege> children, got %d:\n%s", n, got)
	}

	var back Group
	if err := xml.Unmarshal(out, &back); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if back.Privileges == nil || back.Privileges.JssObjects == nil || back.Privileges.JssObjects.Privilege == nil {
		t.Fatal("privileges.jss_objects decoded as nil")
	}
	got2 := *back.Privileges.JssObjects.Privilege
	if len(got2) != 3 {
		t.Fatalf("want 3 privileges after unmarshal, got %d: %v", len(got2), got2)
	}
	for i, want := range privs {
		if got2[i] != want {
			t.Fatalf("privilege[%d]: want %q, got %q", i, want, got2[i])
		}
	}
}

// TestAccountPrivileges_RoundTrip_MarshalXMLCategory mirrors the group test
// for Account privileges (same spec defect, same fix, both must pass).
func TestAccountPrivileges_RoundTrip_MarshalXMLCategory(t *testing.T) {
	privs := []string{"Read Computers", "Update Computers", "Create Computers"}
	a := Account{
		Privileges: &AccountPrivileges{
			CasperAdmin: &AccountPrivilegesCasperAdmin{Privilege: &privs},
		},
	}
	out, err := xml.Marshal(a)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got := string(out)
	if n := strings.Count(got, "<casper_admin>"); n != 1 {
		t.Fatalf("want 1 <casper_admin> wrapper, got %d:\n%s", n, got)
	}
	if n := strings.Count(got, "<privilege>"); n != 3 {
		t.Fatalf("want 3 <privilege> children, got %d:\n%s", n, got)
	}

	var back Account
	if err := xml.Unmarshal(out, &back); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if back.Privileges == nil || back.Privileges.CasperAdmin == nil || back.Privileges.CasperAdmin.Privilege == nil {
		t.Fatal("privileges.casper_admin decoded as nil")
	}
	got2 := *back.Privileges.CasperAdmin.Privilege
	if len(got2) != 3 {
		t.Fatalf("want 3 privileges after unmarshal, got %d: %v", len(got2), got2)
	}
	for i, want := range privs {
		if got2[i] != want {
			t.Fatalf("privilege[%d]: want %q, got %q", i, want, got2[i])
		}
	}
}

// TestAccountPrivileges_RoundTrip_PlainCategory mirrors the plain-category
// group test for Account.
func TestAccountPrivileges_RoundTrip_PlainCategory(t *testing.T) {
	privs := []string{"Create Computers", "Read Computers", "Update Computers"}
	a := Account{
		Privileges: &AccountPrivileges{
			JssObjects: &AccountPrivilegesJssObjects{Privilege: &privs},
		},
	}
	out, err := xml.Marshal(a)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got := string(out)
	if n := strings.Count(got, "<jss_objects>"); n != 1 {
		t.Fatalf("want 1 <jss_objects> wrapper, got %d:\n%s", n, got)
	}
	if n := strings.Count(got, "<privilege>"); n != 3 {
		t.Fatalf("want 3 <privilege> children, got %d:\n%s", n, got)
	}

	var back Account
	if err := xml.Unmarshal(out, &back); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if back.Privileges == nil || back.Privileges.JssObjects == nil || back.Privileges.JssObjects.Privilege == nil {
		t.Fatal("privileges.jss_objects decoded as nil")
	}
	got2 := *back.Privileges.JssObjects.Privilege
	if len(got2) != 3 {
		t.Fatalf("want 3 privileges after unmarshal, got %d: %v", len(got2), got2)
	}
	for i, want := range privs {
		if got2[i] != want {
			t.Fatalf("privilege[%d]: want %q, got %q", i, want, got2[i])
		}
	}
}
