// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"net/http"
	"testing"
)

func TestGetAdvancedComputerSearchByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<advanced_computer_search></advanced_computer_search>")
	})

	result, err := c.GetAdvancedComputerSearchByID(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetAdvancedComputerSearchByID_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/id/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeXML(t, w, http.StatusNotFound, "<error>not found</error>")
	})

	_, err := c.GetAdvancedComputerSearchByID(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestCreateAdvancedComputerSearchByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		writeXML(t, w, http.StatusCreated, "<advanced_computer_search></advanced_computer_search>")
	})

	result, err := c.CreateAdvancedComputerSearchByID(context.Background(), "test-id", &AdvancedComputerSearch{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestUpdateAdvancedComputerSearchByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPut {
			t.Errorf("method = %s, want PUT", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.UpdateAdvancedComputerSearchByID(context.Background(), "test-id", &AdvancedComputerSearch{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestDeleteAdvancedComputerSearchByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(http.StatusOK)
	})

	err := c.DeleteAdvancedComputerSearchByID(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
}

func TestGetAdvancedComputerSearchByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<advanced_computer_search></advanced_computer_search>")
	})

	result, err := c.GetAdvancedComputerSearchByName(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetAdvancedComputerSearchByName_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/name/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeXML(t, w, http.StatusNotFound, "<error>not found</error>")
	})

	_, err := c.GetAdvancedComputerSearchByName(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestDeleteAdvancedComputerSearchByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(http.StatusOK)
	})

	err := c.DeleteAdvancedComputerSearchByName(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
}

func TestListAdvancedComputerSearches(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<advanced_computer_searches></advanced_computer_searches>")
	})

	result, err := c.ListAdvancedComputerSearches(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestListAdvancedComputerSearches_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches", func(w http.ResponseWriter, _ *http.Request) {
		writeXML(t, w, http.StatusNotFound, "<error>not found</error>")
	})

	_, err := c.ListAdvancedComputerSearches(context.Background())
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestUpdateAdvancedComputerSearchByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPut {
			t.Errorf("method = %s, want PUT", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.UpdateAdvancedComputerSearchByName(context.Background(), "test-id", &AdvancedComputerSearch{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestCreateAdvancedComputerSearchByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.CreateAdvancedComputerSearchByName(context.Background(), "test-id", &AdvancedComputerSearch{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestResolveAdvancedComputerSearchIDByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<advanced_computer_search><id>42</id></advanced_computer_search>")
	})

	id, err := c.ResolveAdvancedComputerSearchIDByName(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if id != "42" {
		t.Errorf("id = %q, want 42", id)
	}
}

func TestResolveAdvancedComputerSearchByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<advanced_computer_search><id>42</id></advanced_computer_search>")
	})

	result, err := c.ResolveAdvancedComputerSearchByName(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestApplyAdvancedComputerSearch_Create(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	// Classic direct resolver: GetByName returns 404 → apply creates.
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/name/{name}", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		w.WriteHeader(http.StatusNotFound)
	})
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/id/0", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		writeXML(t, w, 201, "<advanced_computer_search><id>42</id></advanced_computer_search>")
	})

	id, created, err := c.ApplyAdvancedComputerSearch(context.Background(), &AdvancedComputerSearch{Name: ptrStr("target")})
	if err != nil {
		t.Fatal(err)
	}
	if !created {
		t.Error("expected created = true")
	}
	if id != "42" {
		t.Errorf("id = %q, want 42", id)
	}
}

func TestApplyAdvancedComputerSearch_Update(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	// Classic direct resolver: GetByName returns the resource with id=42 → apply updates.
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/name/{name}", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<advanced_computer_search><id>42</id></advanced_computer_search>")
	})
	mux.HandleFunc("/api/proclassic/tenant/t-test/advancedcomputersearches/id/42", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(201)
	})

	id, created, err := c.ApplyAdvancedComputerSearch(context.Background(), &AdvancedComputerSearch{Name: ptrStr("target")})
	if err != nil {
		t.Fatal(err)
	}
	if created {
		t.Error("expected created = false")
	}
	if id != "42" {
		t.Errorf("id = %q, want 42", id)
	}
}
