// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetAllowedFileExtensionByID finds an allowed file extension value by ID.
//
// Required privileges: allowed-file-extension:read.
//
// Parameters:
//   - id: Database ID of the extension.
func (c *Client) GetAllowedFileExtensionByID(ctx context.Context, id string) (*AllowedFileExtension, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result AllowedFileExtension
	endpoint := fmt.Sprintf("%s/allowedfileextensions/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetAllowedFileExtensionByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateAllowedFileExtensionByID creates a new allowed file extension value by ID.
//
// Required privileges: allowed-file-extension:create.
//
// Parameters:
//   - id: Database ID of the extension.
func (c *Client) CreateAllowedFileExtensionByID(ctx context.Context, id string, request *AllowedFileExtension) (*AllowedFileExtension, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result AllowedFileExtension
	endpoint := fmt.Sprintf("%s/allowedfileextensions/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateAllowedFileExtensionByID(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteAllowedFileExtensionByID deletes an allowed file extension value by ID.
//
// Required privileges: allowed-file-extension:delete.
//
// Parameters:
//   - id: Database ID of the extension.
func (c *Client) DeleteAllowedFileExtensionByID(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/allowedfileextensions/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteAllowedFileExtensionByID(%s): %w", id, err)
	}
	return nil
}

// GetAllowedFileExtensionByExtension finds an allowed file extension value by name.
//
// Required privileges: allowed-file-extension:read.
//
// Parameters:
//   - extension: String value of extension.
func (c *Client) GetAllowedFileExtensionByExtension(ctx context.Context, extension string) (*AllowedFileExtension, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result AllowedFileExtension
	endpoint := fmt.Sprintf("%s/allowedfileextensions/extension/%s", prefix, url.PathEscape(extension))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetAllowedFileExtensionByExtension(%s): %w", extension, err)
	}
	return &result, nil
}

// ListAllowedFileExtensions finds the allowed file extensions.
//
// Required privileges: allowed-file-extension:read.
func (c *Client) ListAllowedFileExtensions(ctx context.Context) (*AllowedFileExtensions, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result AllowedFileExtensions
	endpoint := prefix + "/allowedfileextensions"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListAllowedFileExtensions: %w", err)
	}
	return &result, nil
}
