// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"net/http"
	"testing"
)

func TestDeleteCommandFlush(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/proclassic/commandflush", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.DeleteCommandFlush(context.Background(), &Commandflush{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestDeleteCommandFlushByIDTypeIDStatus(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/proclassic/commandflush/test-id/id/test-id/status/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.DeleteCommandFlushByIDTypeIDStatus(context.Background(), "test-id", "test-id", "test-id")
	if err != nil {
		t.Fatal(err)
	}
}
