// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetComputerByID finds computers by id.
//
// Deprecated: this endpoint is marked deprecated in the Jamf API spec and may be removed in a future release.
func (c *Client) GetComputerByID(ctx context.Context, id string) (*Computer, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result Computer
	endpoint := fmt.Sprintf("%s/computers/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerByID(%s): %w", id, err)
	}
	return &result, nil
}
