// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetComputerManagementByID finds computer management information by ID.
func (c *Client) GetComputerManagementByID(ctx context.Context, id string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByID(%s): %w", id, err)
	}
	return &result, nil
}

// GetComputerManagementByName finds computer management information by name.
func (c *Client) GetComputerManagementByName(ctx context.Context, name string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByName(%s): %w", name, err)
	}
	return &result, nil
}

// GetComputerManagementByUDID finds computer management information by UDID.
func (c *Client) GetComputerManagementByUDID(ctx context.Context, udid string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/udid/%s", prefix, url.PathEscape(udid))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByUDID(%s): %w", udid, err)
	}
	return &result, nil
}

// GetComputerManagementBySerialNumber finds computer management information by serial number.
func (c *Client) GetComputerManagementBySerialNumber(ctx context.Context, serialNumber string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/serialnumber/%s", prefix, url.PathEscape(serialNumber))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementBySerialNumber(%s): %w", serialNumber, err)
	}
	return &result, nil
}

// GetComputerManagementByMacAddress finds computer management information by MAC address.
func (c *Client) GetComputerManagementByMacAddress(ctx context.Context, macAddress string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/macaddress/%s", prefix, url.PathEscape(macAddress))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByMacAddress(%s): %w", macAddress, err)
	}
	return &result, nil
}

// GetComputerManagementByIDPatchFilter display patch management information for a computer and filter.
func (c *Client) GetComputerManagementByIDPatchFilter(ctx context.Context, id string, filter string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/id/%s/patchfilter/%s", prefix, url.PathEscape(id), url.PathEscape(filter))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByIDPatchFilter(%s): %w", id, err)
	}
	return &result, nil
}

// GetComputerManagementByIDSubset finds a subset of computer management information by ID.
func (c *Client) GetComputerManagementByIDSubset(ctx context.Context, id string, subset string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/id/%s/subset/%s", prefix, url.PathEscape(id), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByIDSubset(%s): %w", id, err)
	}
	return &result, nil
}

// GetComputerManagementByIDUsername finds management information for a computer and username.
func (c *Client) GetComputerManagementByIDUsername(ctx context.Context, id string, username string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/id/%s/username/%s", prefix, url.PathEscape(id), url.PathEscape(username))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByIDUsername(%s): %w", id, err)
	}
	return &result, nil
}

// GetComputerManagementByIDUsernameSubset finds a subset of management information for a computer and username.
func (c *Client) GetComputerManagementByIDUsernameSubset(ctx context.Context, id string, username string, subset string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/id/%s/username/%s/subset/%s", prefix, url.PathEscape(id), url.PathEscape(username), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByIDUsernameSubset(%s): %w", id, err)
	}
	return &result, nil
}

// GetComputerManagementByMacAddressPatchFilter display patch management information for a computer and filter.
func (c *Client) GetComputerManagementByMacAddressPatchFilter(ctx context.Context, macaddress string, filter string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/macaddress/%s/patchfilter/%s", prefix, url.PathEscape(macaddress), url.PathEscape(filter))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByMacAddressPatchFilter(%s): %w", macaddress, err)
	}
	return &result, nil
}

// GetComputerManagementByMacAddressSubset finds a subset of computer management information by MAC address.
func (c *Client) GetComputerManagementByMacAddressSubset(ctx context.Context, macaddress string, subset string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/macaddress/%s/subset/%s", prefix, url.PathEscape(macaddress), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByMacAddressSubset(%s): %w", macaddress, err)
	}
	return &result, nil
}

// GetComputerManagementByMacAddressUsername finds management information for a computer and username.
func (c *Client) GetComputerManagementByMacAddressUsername(ctx context.Context, macaddress string, username string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/macaddress/%s/username/%s", prefix, url.PathEscape(macaddress), url.PathEscape(username))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByMacAddressUsername(%s): %w", macaddress, err)
	}
	return &result, nil
}

// GetComputerManagementByMacAddressUsernameSubset finds a subset of management information for a computer and username.
func (c *Client) GetComputerManagementByMacAddressUsernameSubset(ctx context.Context, macaddress string, username string, subset string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/macaddress/%s/username/%s/subset/%s", prefix, url.PathEscape(macaddress), url.PathEscape(username), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByMacAddressUsernameSubset(%s): %w", macaddress, err)
	}
	return &result, nil
}

// GetComputerManagementByNamePatchFilter display patch management information for a computer and filter.
func (c *Client) GetComputerManagementByNamePatchFilter(ctx context.Context, name string, filter string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/name/%s/patchfilter/%s", prefix, url.PathEscape(name), url.PathEscape(filter))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByNamePatchFilter(%s): %w", name, err)
	}
	return &result, nil
}

// GetComputerManagementByNameSubset finds a subset of computer management information by name.
func (c *Client) GetComputerManagementByNameSubset(ctx context.Context, name string, subset string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/name/%s/subset/%s", prefix, url.PathEscape(name), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByNameSubset(%s): %w", name, err)
	}
	return &result, nil
}

// GetComputerManagementByNameUsername finds management information for a computer and username.
func (c *Client) GetComputerManagementByNameUsername(ctx context.Context, name string, username string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/name/%s/username/%s", prefix, url.PathEscape(name), url.PathEscape(username))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByNameUsername(%s): %w", name, err)
	}
	return &result, nil
}

// GetComputerManagementByNameUsernameSubset finds a subset of management information for a computer and username.
func (c *Client) GetComputerManagementByNameUsernameSubset(ctx context.Context, name string, username string, subset string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/name/%s/username/%s/subset/%s", prefix, url.PathEscape(name), url.PathEscape(username), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByNameUsernameSubset(%s): %w", name, err)
	}
	return &result, nil
}

// GetComputerManagementBySerialNumberPatchFilter display patch management information for a computer and filter.
func (c *Client) GetComputerManagementBySerialNumberPatchFilter(ctx context.Context, serialnumber string, filter string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/serialnumber/%s/patchfilter/%s", prefix, url.PathEscape(serialnumber), url.PathEscape(filter))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementBySerialNumberPatchFilter(%s): %w", serialnumber, err)
	}
	return &result, nil
}

// GetComputerManagementBySerialNumberSubset finds a subset of computer management information by serial number.
func (c *Client) GetComputerManagementBySerialNumberSubset(ctx context.Context, serialnumber string, subset string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/serialnumber/%s/subset/%s", prefix, url.PathEscape(serialnumber), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementBySerialNumberSubset(%s): %w", serialnumber, err)
	}
	return &result, nil
}

// GetComputerManagementBySerialNumberUsername finds management information for a computer and username.
func (c *Client) GetComputerManagementBySerialNumberUsername(ctx context.Context, serialnumber string, username string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/serialnumber/%s/username/%s", prefix, url.PathEscape(serialnumber), url.PathEscape(username))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementBySerialNumberUsername(%s): %w", serialnumber, err)
	}
	return &result, nil
}

// GetComputerManagementBySerialNumberUsernameSubset finds a subset of management information for a computer and username.
func (c *Client) GetComputerManagementBySerialNumberUsernameSubset(ctx context.Context, serialnumber string, username string, subset string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/serialnumber/%s/username/%s/subset/%s", prefix, url.PathEscape(serialnumber), url.PathEscape(username), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementBySerialNumberUsernameSubset(%s): %w", serialnumber, err)
	}
	return &result, nil
}

// GetComputerManagementByUDIDPatchFilter display patch management information for a computer and filter.
func (c *Client) GetComputerManagementByUDIDPatchFilter(ctx context.Context, udid string, filter string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/udid/%s/patchfilter/%s", prefix, url.PathEscape(udid), url.PathEscape(filter))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByUDIDPatchFilter(%s): %w", udid, err)
	}
	return &result, nil
}

// GetComputerManagementByUDIDSubset finds a subset of computer management information by UDID.
func (c *Client) GetComputerManagementByUDIDSubset(ctx context.Context, udid string, subset string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/udid/%s/subset/%s", prefix, url.PathEscape(udid), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByUDIDSubset(%s): %w", udid, err)
	}
	return &result, nil
}

// GetComputerManagementByUDIDUsername finds management information for a computer and username.
func (c *Client) GetComputerManagementByUDIDUsername(ctx context.Context, udid string, username string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/udid/%s/username/%s", prefix, url.PathEscape(udid), url.PathEscape(username))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByUDIDUsername(%s): %w", udid, err)
	}
	return &result, nil
}

// GetComputerManagementByUDIDUsernameSubset finds a subset of management information for a computer and username.
func (c *Client) GetComputerManagementByUDIDUsernameSubset(ctx context.Context, udid string, username string, subset string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/udid/%s/username/%s/subset/%s", prefix, url.PathEscape(udid), url.PathEscape(username), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByUDIDUsernameSubset(%s): %w", udid, err)
	}
	return &result, nil
}
