// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetComputerManagementByID finds computer management information by ID.
func (c *Client) GetComputerManagementByID(ctx context.Context, id string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByID(%s): %w", id, err)
	}
	return &result, nil
}

// GetComputerManagementByName finds computer management information by name.
func (c *Client) GetComputerManagementByName(ctx context.Context, name string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByName(%s): %w", name, err)
	}
	return &result, nil
}

// GetComputerManagementByUDID finds computer management information by UDID.
func (c *Client) GetComputerManagementByUDID(ctx context.Context, udid string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/udid/%s", prefix, url.PathEscape(udid))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByUDID(%s): %w", udid, err)
	}
	return &result, nil
}

// GetComputerManagementBySerialNumber finds computer management information by serial number.
func (c *Client) GetComputerManagementBySerialNumber(ctx context.Context, serialNumber string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/serialnumber/%s", prefix, url.PathEscape(serialNumber))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementBySerialNumber(%s): %w", serialNumber, err)
	}
	return &result, nil
}

// GetComputerManagementByMacAddress finds computer management information by MAC address.
func (c *Client) GetComputerManagementByMacAddress(ctx context.Context, macAddress string) (*ComputerManagement, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerManagement
	endpoint := fmt.Sprintf("%s/computermanagement/macaddress/%s", prefix, url.PathEscape(macAddress))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerManagementByMacAddress(%s): %w", macAddress, err)
	}
	return &result, nil
}
