// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetComputerGroupByID finds computer groups by ID.
func (c *Client) GetComputerGroupByID(ctx context.Context, id string) (*ComputerGroup, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerGroup
	endpoint := fmt.Sprintf("%s/computergroups/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetComputerGroupByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateComputerGroupByID creates a new computer group by ID.
func (c *Client) CreateComputerGroupByID(ctx context.Context, id string, request *ComputerGroupPost) (*ComputerGroup, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result ComputerGroup
	endpoint := fmt.Sprintf("%s/computergroups/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateComputerGroupByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateComputerGroupByID updates an existing computer group by ID.
func (c *Client) UpdateComputerGroupByID(ctx context.Context, id string, request *ComputerGroupPost) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/computergroups/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateComputerGroupByID(%s): %w", id, err)
	}
	return nil
}

// DeleteComputerGroupByID deletes a computer group by ID.
func (c *Client) DeleteComputerGroupByID(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/computergroups/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteComputerGroupByID(%s): %w", id, err)
	}
	return nil
}
