// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetDepartmentByID finds departments by ID.
func (c *Client) GetDepartmentByID(ctx context.Context, id string) (*Department, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result Department
	endpoint := fmt.Sprintf("%s/departments/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDepartmentByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateDepartmentByID creates a new department by ID.
func (c *Client) CreateDepartmentByID(ctx context.Context, id string, request *Department) (*Department, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result Department
	endpoint := fmt.Sprintf("%s/departments/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateDepartmentByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateDepartmentByID updates an existing department by ID.
func (c *Client) UpdateDepartmentByID(ctx context.Context, id string, request *Department) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/departments/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateDepartmentByID(%s): %w", id, err)
	}
	return nil
}

// DeleteDepartmentByID deletes a department by ID.
func (c *Client) DeleteDepartmentByID(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/departments/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteDepartmentByID(%s): %w", id, err)
	}
	return nil
}

// GetDepartmentByName finds departments by name.
func (c *Client) GetDepartmentByName(ctx context.Context, name string) (*Department, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result Department
	endpoint := fmt.Sprintf("%s/departments/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDepartmentByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdateDepartmentByName updates an existing department by name.
func (c *Client) UpdateDepartmentByName(ctx context.Context, name string, request *Department) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/departments/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateDepartmentByName(%s): %w", name, err)
	}
	return nil
}

// DeleteDepartmentByName deletes a department by name.
func (c *Client) DeleteDepartmentByName(ctx context.Context, name string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/departments/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteDepartmentByName(%s): %w", name, err)
	}
	return nil
}

// ListDepartments finds all departments.
func (c *Client) ListDepartments(ctx context.Context) (*Departments, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result Departments
	endpoint := prefix + "/departments"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListDepartments: %w", err)
	}
	return &result, nil
}
