// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"net/http"
	"testing"
)

func TestGetJsonWebTokenConfigurationByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/jsonwebtokenconfigurations/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<json_web_token_configuration></json_web_token_configuration>")
	})

	result, err := c.GetJsonWebTokenConfigurationByID(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetJsonWebTokenConfigurationByID_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/jsonwebtokenconfigurations/id/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeXML(t, w, http.StatusNotFound, "<error>not found</error>")
	})

	_, err := c.GetJsonWebTokenConfigurationByID(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestCreateJsonWebTokenConfigurationByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/jsonwebtokenconfigurations/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		writeXML(t, w, http.StatusCreated, "<json_web_token_configuration></json_web_token_configuration>")
	})

	result, err := c.CreateJsonWebTokenConfigurationByID(context.Background(), "test-id", &JsonWebTokenConfiguration{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestUpdateJsonWebTokenConfigurationByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/jsonwebtokenconfigurations/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPut {
			t.Errorf("method = %s, want PUT", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.UpdateJsonWebTokenConfigurationByID(context.Background(), "test-id", &JsonWebTokenConfiguration{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestDeleteJsonWebTokenConfigurationByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/jsonwebtokenconfigurations/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(http.StatusOK)
	})

	err := c.DeleteJsonWebTokenConfigurationByID(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
}
