// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetLicensedSoftwareByID finds licensed software by ID.
func (c *Client) GetLicensedSoftwareByID(ctx context.Context, id string) (*LicensedSoftware, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result LicensedSoftware
	endpoint := fmt.Sprintf("%s/licensedsoftware/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetLicensedSoftwareByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateLicensedSoftwareByID creates new licensed software by ID.
func (c *Client) CreateLicensedSoftwareByID(ctx context.Context, id string, request *LicensedSoftware) (*LicensedSoftware, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result LicensedSoftware
	endpoint := fmt.Sprintf("%s/licensedsoftware/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateLicensedSoftwareByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateLicensedSoftwareByID updates existing licensed software by ID.
func (c *Client) UpdateLicensedSoftwareByID(ctx context.Context, id string, request *LicensedSoftware) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/licensedsoftware/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateLicensedSoftwareByID(%s): %w", id, err)
	}
	return nil
}

// DeleteLicensedSoftwareByID deletes licensed software by ID.
func (c *Client) DeleteLicensedSoftwareByID(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/licensedsoftware/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteLicensedSoftwareByID(%s): %w", id, err)
	}
	return nil
}

// GetLicensedSoftwareByName finds licensed software by name.
func (c *Client) GetLicensedSoftwareByName(ctx context.Context, name string) (*LicensedSoftware, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result LicensedSoftware
	endpoint := fmt.Sprintf("%s/licensedsoftware/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetLicensedSoftwareByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdateLicensedSoftwareByName updates an existing licensed software by name.
func (c *Client) UpdateLicensedSoftwareByName(ctx context.Context, name string, request *LicensedSoftware) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/licensedsoftware/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateLicensedSoftwareByName(%s): %w", name, err)
	}
	return nil
}

// DeleteLicensedSoftwareByName deletes licensed software by name.
func (c *Client) DeleteLicensedSoftwareByName(ctx context.Context, name string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/licensedsoftware/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteLicensedSoftwareByName(%s): %w", name, err)
	}
	return nil
}

// ListLicensedSoftware finds all licensed software.
func (c *Client) ListLicensedSoftware(ctx context.Context) (*LicensedSoftwareAll, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result LicensedSoftwareAll
	endpoint := prefix + "/licensedsoftware"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListLicensedSoftware: %w", err)
	}
	return &result, nil
}
