// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetMobileDeviceConfigurationProfileByID finds mobile device configuration profiles by ID.
func (c *Client) GetMobileDeviceConfigurationProfileByID(ctx context.Context, id string) (*MobileDeviceConfigurationProfile, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result MobileDeviceConfigurationProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceconfigurationprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceConfigurationProfileByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateMobileDeviceConfigurationProfileByID creates a new mobile device configuration profile by ID.
func (c *Client) CreateMobileDeviceConfigurationProfileByID(ctx context.Context, id string, request *MobileDeviceConfigurationProfile) (*MobileDeviceConfigurationProfile, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result MobileDeviceConfigurationProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceconfigurationprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateMobileDeviceConfigurationProfileByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateMobileDeviceConfigurationProfileByID updates an existing mobile device configuration profile by ID.
func (c *Client) UpdateMobileDeviceConfigurationProfileByID(ctx context.Context, id string, request *MobileDeviceConfigurationProfile) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/mobiledeviceconfigurationprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateMobileDeviceConfigurationProfileByID(%s): %w", id, err)
	}
	return nil
}

// DeleteMobileDeviceConfigurationProfileByID deletes a mobile device configuration profile by ID.
func (c *Client) DeleteMobileDeviceConfigurationProfileByID(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/mobiledeviceconfigurationprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteMobileDeviceConfigurationProfileByID(%s): %w", id, err)
	}
	return nil
}
