// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetMobileDeviceCommandByUUID finds a mobile device command by UUID.
func (c *Client) GetMobileDeviceCommandByUUID(ctx context.Context, uuid string) (*MobileDeviceCommand, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result MobileDeviceCommand
	endpoint := fmt.Sprintf("%s/mobiledevicecommands/uuid/%s", prefix, url.PathEscape(uuid))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceCommandByUUID(%s): %w", uuid, err)
	}
	return &result, nil
}

// IssueMobileDeviceCommand creates a new mobile device command.
func (c *Client) IssueMobileDeviceCommand(ctx context.Context, request *MobileDeviceCommandPost) (*MobileDeviceCommand, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result MobileDeviceCommand
	endpoint := prefix + "/mobiledevicecommands/command"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/xml", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("IssueMobileDeviceCommand: %w", err)
	}
	return &result, nil
}
