// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"net/http"
	"testing"
)

func TestGetMobileDeviceCommandByUUID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/uuid/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<mobile_device_command></mobile_device_command>")
	})

	result, err := c.GetMobileDeviceCommandByUUID(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetMobileDeviceCommandByUUID_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/uuid/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeXML(t, w, http.StatusNotFound, "<error>not found</error>")
	})

	_, err := c.GetMobileDeviceCommandByUUID(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestIssueMobileDeviceCommand(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/command", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		writeXML(t, w, http.StatusCreated, "<mobile_device_command></mobile_device_command>")
	})

	result, err := c.IssueMobileDeviceCommand(context.Background(), &MobileDeviceCommandPost{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetMobileDeviceCommandByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<mobile_device_command></mobile_device_command>")
	})

	result, err := c.GetMobileDeviceCommandByName(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetMobileDeviceCommandByName_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/name/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeXML(t, w, http.StatusNotFound, "<error>not found</error>")
	})

	_, err := c.GetMobileDeviceCommandByName(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestListMobileDeviceCommands(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<mobile_device_commands></mobile_device_commands>")
	})

	result, err := c.ListMobileDeviceCommands(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestListMobileDeviceCommands_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands", func(w http.ResponseWriter, _ *http.Request) {
		writeXML(t, w, http.StatusNotFound, "<error>not found</error>")
	})

	_, err := c.ListMobileDeviceCommands(context.Background())
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestGetMobileDeviceCommandByCommand(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/command/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<mobile_device_command></mobile_device_command>")
	})

	result, err := c.GetMobileDeviceCommandByCommand(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetMobileDeviceCommandByCommand_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/command/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeXML(t, w, http.StatusNotFound, "<error>not found</error>")
	})

	_, err := c.GetMobileDeviceCommandByCommand(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestCreateMobileDeviceCommandByCommandID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/command/test-id/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.CreateMobileDeviceCommandByCommandID(context.Background(), "test-id", "test-id", &MobileDeviceCommandPost{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestCreateMobileDeviceCommandByCommand(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/command/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.CreateMobileDeviceCommandByCommand(context.Background(), "test-id", &MobileDeviceCommandPost{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestCreateMobileDeviceCommandWithParameterByIDList(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/command/test-id/test-id/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.CreateMobileDeviceCommandWithParameterByIDList(context.Background(), "test-id", "test-id", "test-id", &MobileDeviceCommandPost{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestCreateMobileDeviceCommandWithParameterVersionByIDList(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/command/test-id/test-id/test-id/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.CreateMobileDeviceCommandWithParameterVersionByIDList(context.Background(), "test-id", "test-id", "test-id", "test-id", &MobileDeviceCommandPost{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestCreateMobileDeviceCommandByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/mobiledevicecommands/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.CreateMobileDeviceCommandByName(context.Background(), "test-id", &MobileDeviceCommandPost{})
	if err != nil {
		t.Fatal(err)
	}
}
