// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// GetOSXConfigurationProfileByID finds OS X configuration profiles by ID.
func (c *Client) GetOSXConfigurationProfileByID(ctx context.Context, id string) (*OsXConfigurationProfile, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result OsXConfigurationProfile
	endpoint := fmt.Sprintf("%s/osxconfigurationprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetOSXConfigurationProfileByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateOSXConfigurationProfileByID creates a new OS X configuration profile by ID.
func (c *Client) CreateOSXConfigurationProfileByID(ctx context.Context, id string, request *OsXConfigurationProfile) (*OsXConfigurationProfile, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result OsXConfigurationProfile
	endpoint := fmt.Sprintf("%s/osxconfigurationprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateOSXConfigurationProfileByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateOSXConfigurationProfileByID updates an existing OS X configuration profile by ID.
func (c *Client) UpdateOSXConfigurationProfileByID(ctx context.Context, id string, request *OsXConfigurationProfile) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/osxconfigurationprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateOSXConfigurationProfileByID(%s): %w", id, err)
	}
	return nil
}

// DeleteOSXConfigurationProfileByID deletes a OS X configuration profile by ID.
func (c *Client) DeleteOSXConfigurationProfileByID(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/osxconfigurationprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteOSXConfigurationProfileByID(%s): %w", id, err)
	}
	return nil
}

// GetOSXConfigurationProfileByName finds OS X configuration profiles by name.
func (c *Client) GetOSXConfigurationProfileByName(ctx context.Context, name string) (*OsXConfigurationProfile, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result OsXConfigurationProfile
	endpoint := fmt.Sprintf("%s/osxconfigurationprofiles/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetOSXConfigurationProfileByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdateOSXConfigurationProfileByName updates an existing OS X configuration profile by name.
func (c *Client) UpdateOSXConfigurationProfileByName(ctx context.Context, name string, request *OsXConfigurationProfile) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/osxconfigurationprofiles/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateOSXConfigurationProfileByName(%s): %w", name, err)
	}
	return nil
}

// DeleteOSXConfigurationProfileByName deletes a OS X configuration profile by name.
func (c *Client) DeleteOSXConfigurationProfileByName(ctx context.Context, name string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/osxconfigurationprofiles/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteOSXConfigurationProfileByName(%s): %w", name, err)
	}
	return nil
}

// ListOSXConfigurationProfiles finds all OS X configuration profiles.
func (c *Client) ListOSXConfigurationProfiles(ctx context.Context) (*OsXConfigurationProfiles, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result OsXConfigurationProfiles
	endpoint := prefix + "/osxconfigurationprofiles"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListOSXConfigurationProfiles: %w", err)
	}
	return &result, nil
}

// GetOsxConfigurationProfileByIDSubset finds a subset of data for an OS X configuration profile.
func (c *Client) GetOsxConfigurationProfileByIDSubset(ctx context.Context, id string, subset string) (*OsXConfigurationProfile, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result OsXConfigurationProfile
	endpoint := fmt.Sprintf("%s/osxconfigurationprofiles/id/%s/subset/%s", prefix, url.PathEscape(id), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetOsxConfigurationProfileByIDSubset(%s): %w", id, err)
	}
	return &result, nil
}

// GetOsxConfigurationProfileByNameSubset finds a subset of data for OS X configuration profiles by name.
func (c *Client) GetOsxConfigurationProfileByNameSubset(ctx context.Context, name string, subset string) (*OsXConfigurationProfile, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result OsXConfigurationProfile
	endpoint := fmt.Sprintf("%s/osxconfigurationprofiles/name/%s/subset/%s", prefix, url.PathEscape(name), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetOsxConfigurationProfileByNameSubset(%s): %w", name, err)
	}
	return &result, nil
}

// ResolveOSXConfigurationProfileIDByName looks up a OSXConfigurationProfile by name via GetOSXConfigurationProfileByName and returns its ID as a string. Returns an error when the underlying call returns a nil ID.
func (c *Client) ResolveOSXConfigurationProfileIDByName(ctx context.Context, name string) (string, error) {
	r, err := c.GetOSXConfigurationProfileByName(ctx, name)
	if err != nil {
		return "", fmt.Errorf("ResolveOSXConfigurationProfileIDByName(%s): %w", name, err)
	}
	if r == nil || r.General == nil || r.General.ID == nil {
		return "", fmt.Errorf("ResolveOSXConfigurationProfileIDByName(%s): response missing id", name)
	}
	return strconv.Itoa(*r.General.ID), nil
}

// ResolveOSXConfigurationProfileByName looks up a OSXConfigurationProfile by name. Alias for GetOSXConfigurationProfileByName; present so callers can use the same Resolve<X>ByName spelling across all resources regardless of resolver mode.
func (c *Client) ResolveOSXConfigurationProfileByName(ctx context.Context, name string) (*OsXConfigurationProfile, error) {
	return c.GetOSXConfigurationProfileByName(ctx, name)
}
