// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"net/http"
	"testing"
)

func TestGetClassicPackageByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<package></package>")
	})

	result, err := c.GetClassicPackageByID(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetClassicPackageByID_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/id/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeXML(t, w, http.StatusNotFound, "<error>not found</error>")
	})

	_, err := c.GetClassicPackageByID(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestCreateClassicPackageByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		writeXML(t, w, http.StatusCreated, "<package></package>")
	})

	result, err := c.CreateClassicPackageByID(context.Background(), "test-id", &Package{})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestUpdateClassicPackageByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPut {
			t.Errorf("method = %s, want PUT", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.UpdateClassicPackageByID(context.Background(), "test-id", &Package{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestDeleteClassicPackageByID(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/id/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(http.StatusOK)
	})

	err := c.DeleteClassicPackageByID(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
}

func TestListClassicPackages(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<packages></packages>")
	})

	result, err := c.ListClassicPackages(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestListClassicPackages_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages", func(w http.ResponseWriter, _ *http.Request) {
		writeXML(t, w, http.StatusNotFound, "<error>not found</error>")
	})

	_, err := c.ListClassicPackages(context.Background())
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestDeleteClassicPackageByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(http.StatusOK)
	})

	err := c.DeleteClassicPackageByName(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
}

func TestGetClassicPackageByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<package></package>")
	})

	result, err := c.GetClassicPackageByName(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestGetClassicPackageByName_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/name/test-id", func(w http.ResponseWriter, _ *http.Request) {
		writeXML(t, w, http.StatusNotFound, "<error>not found</error>")
	})

	_, err := c.GetClassicPackageByName(context.Background(), "test-id")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestUpdateClassicPackageByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPut {
			t.Errorf("method = %s, want PUT", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.UpdateClassicPackageByName(context.Background(), "test-id", &Package{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestCreateClassicPackageByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.WriteHeader(http.StatusCreated)
	})

	err := c.CreateClassicPackageByName(context.Background(), "test-id", &Package{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestResolveClassicPackageIDByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<package><id>42</id></package>")
	})

	id, err := c.ResolveClassicPackageIDByName(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if id != "42" {
		t.Errorf("id = %q, want 42", id)
	}
}

func TestResolveClassicPackageByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/name/test-id", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<package><id>42</id></package>")
	})

	result, err := c.ResolveClassicPackageByName(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestApplyClassicPackage_Create(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	// Classic direct resolver: GetByName returns 404 → apply creates.
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/name/{name}", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		w.WriteHeader(http.StatusNotFound)
	})
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/id/0", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("method = %s, want POST", r.Method)
		}
		writeXML(t, w, 201, "<package><id>42</id></package>")
	})

	id, created, err := c.ApplyClassicPackage(context.Background(), &Package{Name: ptrStr("target")})
	if err != nil {
		t.Fatal(err)
	}
	if !created {
		t.Error("expected created = true")
	}
	if id != "42" {
		t.Errorf("id = %q, want 42", id)
	}
}

func TestApplyClassicPackage_Update(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	// Classic direct resolver: GetByName returns the resource with id=42 → apply updates.
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/name/{name}", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeXML(t, w, http.StatusOK, "<package><id>42</id></package>")
	})
	mux.HandleFunc("/api/proclassic/tenant/t-test/packages/id/42", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(201)
	})

	id, created, err := c.ApplyClassicPackage(context.Background(), &Package{Name: ptrStr("target")})
	if err != nil {
		t.Fatal(err)
	}
	if created {
		t.Error("expected created = false")
	}
	if id != "42" {
		t.Errorf("id = %q, want 42", id)
	}
}
