// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetPatchReportByPatchSoftwareTitleID finds patch reports by patch software title ID. (Deprecated) Please transition use to Jamf Pro API endpoint "/v2/patch-software-title-configurations/{id}/patch-report".
//
// Deprecated: this endpoint is marked deprecated in the Jamf API spec and may be removed in a future release.
func (c *Client) GetPatchReportByPatchSoftwareTitleID(ctx context.Context, id string) (*PatchReport, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result PatchReport
	endpoint := fmt.Sprintf("%s/patchreports/patchsoftwaretitleid/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPatchReportByPatchSoftwareTitleID(%s): %w", id, err)
	}
	return &result, nil
}
