// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetPatchExternalSourceByID finds a patch external source by ID.
func (c *Client) GetPatchExternalSourceByID(ctx context.Context, id string) (*PatchExternalSource, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result PatchExternalSource
	endpoint := fmt.Sprintf("%s/patchexternalsources/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPatchExternalSourceByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreatePatchExternalSourceByID create a new patch external source by ID.
func (c *Client) CreatePatchExternalSourceByID(ctx context.Context, id string, request *PatchExternalSource) (*PatchExternalSource, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result PatchExternalSource
	endpoint := fmt.Sprintf("%s/patchexternalsources/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreatePatchExternalSourceByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdatePatchExternalSourceByID updates a patch external source by ID.
func (c *Client) UpdatePatchExternalSourceByID(ctx context.Context, id string, request *PatchExternalSource) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/patchexternalsources/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdatePatchExternalSourceByID(%s): %w", id, err)
	}
	return nil
}

// DeletePatchExternalSourceByID deletes a patch external source by ID.
func (c *Client) DeletePatchExternalSourceByID(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/patchexternalsources/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeletePatchExternalSourceByID(%s): %w", id, err)
	}
	return nil
}
