// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetPeripheralByID finds peripherals by ID.
func (c *Client) GetPeripheralByID(ctx context.Context, id string) (*Peripheral, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result Peripheral
	endpoint := fmt.Sprintf("%s/peripherals/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPeripheralByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreatePeripheralByID creates a new peripheral by ID.
func (c *Client) CreatePeripheralByID(ctx context.Context, id string, request *PeripheralPost) (*Peripheral, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result Peripheral
	endpoint := fmt.Sprintf("%s/peripherals/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreatePeripheralByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdatePeripheralByID updates an existing peripheral by ID.
func (c *Client) UpdatePeripheralByID(ctx context.Context, id string, request *PeripheralPost) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/peripherals/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdatePeripheralByID(%s): %w", id, err)
	}
	return nil
}

// DeletePeripheralByID deletes a peripheral by ID.
func (c *Client) DeletePeripheralByID(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/peripherals/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeletePeripheralByID(%s): %w", id, err)
	}
	return nil
}
