// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// GetPrinterByID finds printers by ID.
func (c *Client) GetPrinterByID(ctx context.Context, id string) (*Printer, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result Printer
	endpoint := fmt.Sprintf("%s/printers/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPrinterByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreatePrinterByID creates a new printer by ID.
func (c *Client) CreatePrinterByID(ctx context.Context, id string, request *Printer) (*Printer, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result Printer
	endpoint := fmt.Sprintf("%s/printers/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreatePrinterByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdatePrinterByID updates an existing printer by ID.
func (c *Client) UpdatePrinterByID(ctx context.Context, id string, request *Printer) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/printers/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdatePrinterByID(%s): %w", id, err)
	}
	return nil
}

// DeletePrinterByID deletes a printer by ID.
func (c *Client) DeletePrinterByID(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/printers/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeletePrinterByID(%s): %w", id, err)
	}
	return nil
}

// GetPrinterByName finds printers by name.
func (c *Client) GetPrinterByName(ctx context.Context, name string) (*Printer, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result Printer
	endpoint := fmt.Sprintf("%s/printers/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPrinterByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdatePrinterByName updates an existing printer by name.
func (c *Client) UpdatePrinterByName(ctx context.Context, name string, request *Printer) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/printers/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdatePrinterByName(%s): %w", name, err)
	}
	return nil
}

// DeletePrinterByName deletes a printer by name.
func (c *Client) DeletePrinterByName(ctx context.Context, name string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/printers/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeletePrinterByName(%s): %w", name, err)
	}
	return nil
}

// ListPrinters finds all printers.
func (c *Client) ListPrinters(ctx context.Context) (*Printers, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result Printers
	endpoint := prefix + "/printers"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListPrinters: %w", err)
	}
	return &result, nil
}

// ResolvePrinterIDByName looks up a Printer by name via GetPrinterByName and returns its ID as a string. Returns an error when the underlying call returns a nil ID.
func (c *Client) ResolvePrinterIDByName(ctx context.Context, name string) (string, error) {
	r, err := c.GetPrinterByName(ctx, name)
	if err != nil {
		return "", fmt.Errorf("ResolvePrinterIDByName(%s): %w", name, err)
	}
	if r == nil || r.ID == nil {
		return "", fmt.Errorf("ResolvePrinterIDByName(%s): response missing id", name)
	}
	return strconv.Itoa(*r.ID), nil
}

// ResolvePrinterByName looks up a Printer by name. Alias for GetPrinterByName; present so callers can use the same Resolve<X>ByName spelling across all resources regardless of resolver mode.
func (c *Client) ResolvePrinterByName(ctx context.Context, name string) (*Printer, error) {
	return c.GetPrinterByName(ctx, name)
}
