// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetSoftwareUpdateServerByID finds software update servers by ID.
func (c *Client) GetSoftwareUpdateServerByID(ctx context.Context, id string) (*SoftwareUpdateServer, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result SoftwareUpdateServer
	endpoint := fmt.Sprintf("%s/softwareupdateservers/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetSoftwareUpdateServerByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateSoftwareUpdateServerByID creates a new software update server by ID.
func (c *Client) CreateSoftwareUpdateServerByID(ctx context.Context, id string, request *SoftwareUpdateServer) (*SoftwareUpdateServer, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result SoftwareUpdateServer
	endpoint := fmt.Sprintf("%s/softwareupdateservers/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateSoftwareUpdateServerByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateSoftwareUpdateServerByID updates an existing software update server by ID.
func (c *Client) UpdateSoftwareUpdateServerByID(ctx context.Context, id string, request *SoftwareUpdateServer) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/softwareupdateservers/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateSoftwareUpdateServerByID(%s): %w", id, err)
	}
	return nil
}

// DeleteSoftwareUpdateServerByID deletes a software update server by ID.
func (c *Client) DeleteSoftwareUpdateServerByID(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/softwareupdateservers/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteSoftwareUpdateServerByID(%s): %w", id, err)
	}
	return nil
}
