// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetUserExtensionAttributeByID finds user extension attributes by ID.
func (c *Client) GetUserExtensionAttributeByID(ctx context.Context, id string) (*UserExtensionAttribute, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result UserExtensionAttribute
	endpoint := fmt.Sprintf("%s/userextensionattributes/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetUserExtensionAttributeByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateUserExtensionAttributeByID creates a new user extension attribute by ID.
func (c *Client) CreateUserExtensionAttributeByID(ctx context.Context, id string, request *UserExtensionAttribute) (*UserExtensionAttribute, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result UserExtensionAttribute
	endpoint := fmt.Sprintf("%s/userextensionattributes/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateUserExtensionAttributeByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateUserExtensionAttributeByID updates an existing user extension attribute by ID.
func (c *Client) UpdateUserExtensionAttributeByID(ctx context.Context, id string, request *UserExtensionAttribute) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/userextensionattributes/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateUserExtensionAttributeByID(%s): %w", id, err)
	}
	return nil
}

// DeleteUserExtensionAttributeByID deletes a user extension attribute by ID.
func (c *Client) DeleteUserExtensionAttributeByID(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/userextensionattributes/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteUserExtensionAttributeByID(%s): %w", id, err)
	}
	return nil
}

// GetUserExtensionAttributeByName finds user extension attributes by name.
func (c *Client) GetUserExtensionAttributeByName(ctx context.Context, name string) (*UserExtensionAttribute, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result UserExtensionAttribute
	endpoint := fmt.Sprintf("%s/userextensionattributes/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetUserExtensionAttributeByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdateUserExtensionAttributeByName updates an existing user extension attribute by name.
func (c *Client) UpdateUserExtensionAttributeByName(ctx context.Context, name string, request *UserExtensionAttribute) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/userextensionattributes/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateUserExtensionAttributeByName(%s): %w", name, err)
	}
	return nil
}

// DeleteUserExtensionAttributeByName deletes a user extension attribute by name.
func (c *Client) DeleteUserExtensionAttributeByName(ctx context.Context, name string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/userextensionattributes/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteUserExtensionAttributeByName(%s): %w", name, err)
	}
	return nil
}
