// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetUserByID finds users by ID.
func (c *Client) GetUserByID(ctx context.Context, id string) (*User, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result User
	endpoint := fmt.Sprintf("%s/users/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetUserByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateUserByID creates a new user by ID.
func (c *Client) CreateUserByID(ctx context.Context, id string, request *UserPost) (*User, error) {
	prefix := c.transport.TenantPrefix("proclassic", "")
	var result User
	endpoint := fmt.Sprintf("%s/users/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateUserByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateUserByID updates an existing user by ID.
func (c *Client) UpdateUserByID(ctx context.Context, id string, request *UserPost) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/users/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateUserByID(%s): %w", id, err)
	}
	return nil
}

// DeleteUserByID deletes a user by ID.
func (c *Client) DeleteUserByID(ctx context.Context, id string) error {
	prefix := c.transport.TenantPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/users/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteUserByID(%s): %w", id, err)
	}
	return nil
}
