// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package devices

import "github.com/Jamf-Concepts/jamfplatform-go-sdk/jamfplatform"

// Privileges maps each devices SDK method name to the Jamf API privileges it
// requires, sourced from the x-required-privileges vendor extensions in the
// Jamf OpenAPI specs. Methods that require no special privilege have an empty
// Scoped slice. Synthetic Resolve<X>ByName / Apply<X> methods are not present;
// document the privileges of the operations they call instead.
var Privileges = map[string]jamfplatform.MethodPrivileges{
	"DeleteDevice":           {Method: "DeleteDevice", HTTPMethod: "DELETE", Path: "/v1/devices/{id}", Scoped: []string{"destructive-device-actions:execute"}, Legacy: nil},
	"GetDevice":              {Method: "GetDevice", HTTPMethod: "GET", Path: "/v1/devices/{id}", Scoped: []string{"devices:read"}, Legacy: nil},
	"ListDeviceApplications": {Method: "ListDeviceApplications", HTTPMethod: "GET", Path: "/v1/devices/{id}/applications", Scoped: []string{"devices:read"}, Legacy: nil},
	"ListDevices":            {Method: "ListDevices", HTTPMethod: "GET", Path: "/v1/devices", Scoped: []string{"devices:read"}, Legacy: nil},
	"ListDevicesForUser":     {Method: "ListDevicesForUser", HTTPMethod: "GET", Path: "/v1/users/{id}/devices", Scoped: []string{"devices:read"}, Legacy: nil},
	"UpdateDevice":           {Method: "UpdateDevice", HTTPMethod: "PATCH", Path: "/v1/devices/{id}", Scoped: []string{"devices:update"}, Legacy: nil},
}

// PrivilegesFor returns the privilege metadata for the named SDK method and
// true when the method is present in the registry, or the zero value and
// false otherwise.
func PrivilegesFor(method string) (jamfplatform.MethodPrivileges, bool) {
	p, ok := Privileges[method]
	return p, ok
}
