// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package jamfplatform

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

// ApiErrorDto represents a api error dto.
type ApiErrorDto struct {
	Errors     []ErrorDto `json:"errors"`
	HttpStatus int        `json:"httpStatus"`
	TraceID    string     `json:"traceId"`
}

// DeclarationReportClientDto represents a declaration report client dto.
type DeclarationReportClientDto struct {
	Active        bool                               `json:"active"`
	Channel       string                             `json:"channel"`
	DateUpdated   string                             `json:"dateUpdated"`
	DeviceID      string                             `json:"deviceId"`
	Reasons       []StatusReportDeclarationReasonDto `json:"reasons"`
	ServerToken   string                             `json:"serverToken"`
	ValidityState string                             `json:"validityState"`
}

// DeclarationReportDto represents a declaration report dto.
type DeclarationReportDto struct {
	DeclarationIdentifier string                       `json:"declarationIdentifier"`
	Results               []DeclarationReportClientDto `json:"results"`
	TotalCount            int64                        `json:"totalCount"`
}

// DeviceReportChannelDto represents a device report channel dto.
type DeviceReportChannelDto struct {
	Channel        string                       `json:"channel"`
	Declarations   []StatusReportDeclarationDto `json:"declarations"`
	LastReportTime string                       `json:"lastReportTime"`
}

// DeviceReportDto represents a device report dto.
type DeviceReportDto struct {
	Channels []DeviceReportChannelDto `json:"channels"`
}

// ErrorDto represents a error dto.
type ErrorDto struct {
	Code        string `json:"code"`
	Description string `json:"description"`
	Field       string `json:"field"`
	ID          string `json:"id"`
}

// StatusReportDeclarationDto represents a status report declaration dto.
type StatusReportDeclarationDto struct {
	Active                bool                               `json:"active"`
	DateUpdated           string                             `json:"dateUpdated"`
	DeclarationIdentifier string                             `json:"declarationIdentifier"`
	Reasons               []StatusReportDeclarationReasonDto `json:"reasons"`
	ServerToken           string                             `json:"serverToken"`
	Status                string                             `json:"status"`
	Type                  string                             `json:"type"`
	ValidityState         string                             `json:"validityState"`
}

// StatusReportDeclarationReasonDetailDto represents a status report declaration reason detail dto.
type StatusReportDeclarationReasonDetailDto struct {
	Description string `json:"description"`
	Key         string `json:"key"`
}

// StatusReportDeclarationReasonDto represents a status report declaration reason dto.
type StatusReportDeclarationReasonDto struct {
	Code        string                                   `json:"code"`
	Description string                                   `json:"description"`
	Details     []StatusReportDeclarationReasonDetailDto `json:"details"`
}

// ---------------------------------------------------------------------------
// Methods
// ---------------------------------------------------------------------------

// GetDeviceDeclarationReport get device report declarations.
func (c *Client) GetDeviceDeclarationReport(ctx context.Context, deviceID string) (*DeviceReportDto, error) {
	prefix := c.tenantPrefix("ddm/report", "v1")
	var result DeviceReportDto
	endpoint := fmt.Sprintf("%s/devices/%s", prefix, url.PathEscape(deviceID))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDeviceDeclarationReport(%s): %w", deviceID, err)
	}
	return &result, nil
}

// ListDeclarationReportClients get declaration report devices.
func (c *Client) ListDeclarationReportClients(ctx context.Context, declarationIdentifier string, sort []string) ([]DeclarationReportClientDto, error) {
	prefix := c.tenantPrefix("ddm/report", "v1")
	return client.ListAllPages(ctx, func(ctx context.Context, page, pageSize int) ([]DeclarationReportClientDto, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}

		endpoint := fmt.Sprintf("%s/declarations/%s", prefix, url.PathEscape(declarationIdentifier))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                          `json:"totalCount"`
			Results    []DeclarationReportClientDto `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}
