// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package securitycloud

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ListActivationProfilesV1 search activation profiles.
//
// Required privileges: none (callable by any authenticated API client).
//
// Parameters:
//   - origin: Creation origin - the feature or context that created the activation profile.
//     Allowed values: "PUBLIC_API".
func (c *Client) ListActivationProfilesV1(ctx context.Context, origin string) (*ActivationProfilesResponse, error) {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	var result ActivationProfilesResponse
	endpoint := prefix + "/activation-profiles"
	params := url.Values{}
	if origin != "" {
		params.Set("origin", origin)
	}
	if encoded := params.Encode(); encoded != "" {
		endpoint += "?" + encoded
	}
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListActivationProfilesV1: %w", err)
	}
	return &result, nil
}

// CreateActivationProfileV1 create activation profile.
//
// Required privileges: none (callable by any authenticated API client).
func (c *Client) CreateActivationProfileV1(ctx context.Context, request *PublicApiCreateActivationProfileRequest) (*ActivationProfileResponse, error) {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	var result ActivationProfileResponse
	endpoint := prefix + "/activation-profiles"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateActivationProfileV1: %w", err)
	}
	return &result, nil
}

// DeleteActivationProfilesV1 delete multiple activation profiles.
//
// Required privileges: none (callable by any authenticated API client).
func (c *Client) DeleteActivationProfilesV1(ctx context.Context, request *BulkDeleteActivationProfilesRequest) error {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	endpoint := prefix + "/activation-profiles/delete-multiple"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteActivationProfilesV1: %w", err)
	}
	return nil
}

// PauseActivationProfileV1 pause activation profile.
//
// Required privileges: none (callable by any authenticated API client).
//
// Parameters:
//   - activationProfileID: Unique code identifying the activation profile.
func (c *Client) PauseActivationProfileV1(ctx context.Context, activationProfileID string) error {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	endpoint := fmt.Sprintf("%s/activation-profiles/%s/pause", prefix, url.PathEscape(activationProfileID))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("PauseActivationProfileV1(%s): %w", activationProfileID, err)
	}
	return nil
}

// ResumeActivationProfileV1 resume activation profile.
//
// Required privileges: none (callable by any authenticated API client).
//
// Parameters:
//   - activationProfileID: Unique code identifying the activation profile.
func (c *Client) ResumeActivationProfileV1(ctx context.Context, activationProfileID string) error {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	endpoint := fmt.Sprintf("%s/activation-profiles/%s/resume", prefix, url.PathEscape(activationProfileID))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("ResumeActivationProfileV1(%s): %w", activationProfileID, err)
	}
	return nil
}

// GetActivationProfileV1 get activation profile.
//
// Required privileges: none (callable by any authenticated API client).
//
// Parameters:
//   - activationProfileID: Unique code identifying the activation profile.
func (c *Client) GetActivationProfileV1(ctx context.Context, activationProfileID string) (*ActivationProfile, error) {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	var result ActivationProfile
	endpoint := fmt.Sprintf("%s/activation-profiles/%s", prefix, url.PathEscape(activationProfileID))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetActivationProfileV1(%s): %w", activationProfileID, err)
	}
	return &result, nil
}
