// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package securitycloud

import (
	"context"
	"net/http"
	"testing"
)

func TestListContentCategoriesV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/securitycloud/v1/tenant/t-test/categories", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{})
	})

	result, err := c.ListContentCategoriesV1(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}

func TestListContentCategoriesV1_NotFound(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/securitycloud/v1/tenant/t-test/categories", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(t, w, http.StatusNotFound, map[string]any{
			"httpStatus": 404,
			"traceId":    "trace-nf",
			"errors":     []map[string]string{{"code": "NOT_FOUND", "field": "id", "description": "not found"}},
		})
	})

	_, err := c.ListContentCategoriesV1(context.Background())
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestResolveContentCategoryV1IDByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/securitycloud/v1/tenant/t-test/categories", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{
			"results": []map[string]any{
				{"id": "resolved-id", "displayName": "target"},
			},
			"totalCount": 1,
		})
	})

	id, err := c.ResolveContentCategoryV1IDByName(context.Background(), "target")
	if err != nil {
		t.Fatal(err)
	}
	if id != "resolved-id" {
		t.Errorf("id = %q, want resolved-id", id)
	}
}

func TestResolveContentCategoryV1ByName(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/securitycloud/v1/tenant/t-test/categories", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %s, want GET", r.Method)
		}
		writeJSON(t, w, http.StatusOK, map[string]any{
			"results": []map[string]any{
				{"id": "resolved-id", "displayName": "target"},
			},
			"totalCount": 1,
		})
	})

	result, err := c.ResolveContentCategoryV1ByName(context.Background(), "target")
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
}
