// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package securitycloud

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// EnableUemConnectorV1 enable connector synchronization.
//
// Required privileges: uem-connect:update.
//
// Parameters:
//   - configID: The connector configuration identifier.
func (c *Client) EnableUemConnectorV1(ctx context.Context, configID string, request *EnablementRequest) error {
	prefix := c.transport.APIPrefix("securitycloud", "")
	endpoint := fmt.Sprintf("%s/uem-connect/v1/connectors/%s/enablement", prefix, url.PathEscape(configID))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("EnableUemConnectorV1(%s): %w", configID, err)
	}
	return nil
}

// DisableUemConnectorV1 disable connector synchronization.
//
// Required privileges: uem-connect:delete.
//
// Parameters:
//   - configID: The connector configuration identifier.
func (c *Client) DisableUemConnectorV1(ctx context.Context, configID string) error {
	prefix := c.transport.APIPrefix("securitycloud", "")
	endpoint := fmt.Sprintf("%s/uem-connect/v1/connectors/%s/enablement", prefix, url.PathEscape(configID))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DisableUemConnectorV1(%s): %w", configID, err)
	}
	return nil
}
