// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package securitycloud

import (
	"context"
	"net/http"
	"testing"
)

func TestEnableUemConnectorV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/securitycloud/tenant/t-test/uem-connect/v1/connectors/test-id/enablement", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPut {
			t.Errorf("method = %s, want PUT", r.Method)
		}
		w.WriteHeader(http.StatusNoContent)
	})

	err := c.EnableUemConnectorV1(context.Background(), "test-id", &EnablementRequest{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestDisableUemConnectorV1(t *testing.T) {
	c, mux := testServerWithOpts(t, WithTenantID("t-test"))
	mux.HandleFunc("/api/securitycloud/tenant/t-test/uem-connect/v1/connectors/test-id/enablement", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(http.StatusNoContent)
	})

	err := c.DisableUemConnectorV1(context.Background(), "test-id")
	if err != nil {
		t.Fatal(err)
	}
}
