// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package securitycloud

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ListZtnaGatewaysV1 list Gateways.
//
// Required privileges: read:jsc:all.
func (c *Client) ListZtnaGatewaysV1(ctx context.Context) ([]Gateway, error) {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	return client.ListAllPages(ctx, 100, func(ctx context.Context, page, pageSize int) ([]Gateway, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))

		endpoint := prefix + "/ztna/gateways"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int       `json:"totalCount"`
			Results    []Gateway `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateZtnaGatewayV1 create a Gateway.
//
// Required privileges: create:jsc:all.
func (c *Client) CreateZtnaGatewayV1(ctx context.Context, request *GatewayCreateRequest) (*CreateResponse, error) {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	var result CreateResponse
	endpoint := prefix + "/ztna/gateways"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateZtnaGatewayV1: %w", err)
	}
	return &result, nil
}

// GetZtnaGatewayV1 get a Gateway.
//
// Required privileges: read:jsc:all.
//
// Parameters:
//   - gatewayID: ID of the Gateway (obtained from `GET /gateways` or a create response). Format: 4-character
//     lowercase hexadecimal string (e.g. `a1b2`).
func (c *Client) GetZtnaGatewayV1(ctx context.Context, gatewayID string) (*Gateway, error) {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	var result Gateway
	endpoint := fmt.Sprintf("%s/ztna/gateways/%s", prefix, url.PathEscape(gatewayID))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetZtnaGatewayV1(%s): %w", gatewayID, err)
	}
	return &result, nil
}

// UpdateZtnaGatewayV1 partially update a Gateway.
//
// Required privileges: update:jsc:all.
//
// Parameters:
//   - gatewayID: ID of the Gateway (obtained from `GET /gateways` or a create response). Format: 4-character
//     lowercase hexadecimal string (e.g. `a1b2`).
func (c *Client) UpdateZtnaGatewayV1(ctx context.Context, gatewayID string, request *GatewayPatchRequest) error {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	endpoint := fmt.Sprintf("%s/ztna/gateways/%s", prefix, url.PathEscape(gatewayID))
	if err := c.transport.DoWithContentType(ctx, http.MethodPatch, endpoint, request, "application/merge-patch+json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("UpdateZtnaGatewayV1(%s): %w", gatewayID, err)
	}
	return nil
}

// DeleteZtnaGatewayV1 delete a Gateway.
//
// Required privileges: delete:jsc:all.
//
// Parameters:
//   - gatewayID: ID of the Gateway (obtained from `GET /gateways` or a create response). Format: 4-character
//     lowercase hexadecimal string (e.g. `a1b2`).
func (c *Client) DeleteZtnaGatewayV1(ctx context.Context, gatewayID string) error {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	endpoint := fmt.Sprintf("%s/ztna/gateways/%s", prefix, url.PathEscape(gatewayID))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteZtnaGatewayV1(%s): %w", gatewayID, err)
	}
	return nil
}
