// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package securitycloud

import (
	"context"
	"fmt"
	"net/http"
)

// ListZtnaPredefinedAppsV1 list Predefined Apps.
//
// Required privileges: read:jsc:all.
func (c *Client) ListZtnaPredefinedAppsV1(ctx context.Context) (*PredefinedAppListResponse, error) {
	prefix := c.transport.TenantPrefix("securitycloud", "v1")
	var result PredefinedAppListResponse
	endpoint := prefix + "/ztna/predefined-apps"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListZtnaPredefinedAppsV1: %w", err)
	}
	return &result, nil
}
