// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package securitycloud

import (
	"context"
	"fmt"
	"net/http"
)

// ListZtnaSharedGatewaysV1 list Shared Gateways.
//
// Required privileges: read:jsc:all.
func (c *Client) ListZtnaSharedGatewaysV1(ctx context.Context) (*SharedGatewayListResponse, error) {
	prefix := c.transport.APIPrefix("securitycloud", "v1")
	var result SharedGatewayListResponse
	endpoint := prefix + "/ztna/shared-gateways"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListZtnaSharedGatewaysV1: %w", err)
	}
	return &result, nil
}
