// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package account

import (
	"context"
	"fmt"
	"net/http"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ListDealRegistrations list Deal Registrations.
//
// Required privileges: the spec declares none.
func (c *Client) ListDealRegistrations(ctx context.Context) ([]DealRegistration, error) {
	prefix := c.transport.APIPrefix("partners", "v1")
	endpoint := prefix + "/deal-registrations"

	results, err := client.UnwrapResults[DealRegistration](ctx, c.transport, http.MethodGet, endpoint, "results")
	if err != nil {
		return nil, fmt.Errorf("ListDealRegistrations: %w", err)
	}
	return results, nil
}
