// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package account

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetDistributorQuote get Distributor Quote.
//
// Required privileges: distributor-actions:read.
// The published spec declares none for this operation; these are the
// capabilities the gateway's own authorization policy enforces. See
// Privileges in this package for the provenance.
//
// Parameters:
//   - quoteNumber: Jamf-assigned quote number, as returned in the `quoteNumber` field of a quote.
func (c *Client) GetDistributorQuote(ctx context.Context, quoteNumber string) (*DistributorQuote, error) {
	prefix := c.transport.APIPrefix("partners", "v1")
	var result DistributorQuote
	endpoint := fmt.Sprintf("%s/distributor/quotes/%s", prefix, url.PathEscape(quoteNumber))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDistributorQuote(%s): %w", quoteNumber, err)
	}
	return &result, nil
}
