// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package account

import (
	"context"
	"fmt"
	"net/http"
)

// GetDistributorConfiguration get Distributor Configuration.
//
// Required privileges: the spec declares none.
func (c *Client) GetDistributorConfiguration(ctx context.Context) (*DistributorConfiguration, error) {
	prefix := c.transport.APIPrefix("partners", "v1")
	var result DistributorConfiguration
	endpoint := prefix + "/distributor/configuration"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDistributorConfiguration: %w", err)
	}
	return &result, nil
}

// UpdateDistributorConfiguration update Distributor Configuration.
//
// Required privileges: the spec declares none.
func (c *Client) UpdateDistributorConfiguration(ctx context.Context, request *DistributorConfiguration) error {
	prefix := c.transport.APIPrefix("partners", "v1")
	endpoint := prefix + "/distributor/configuration"
	if err := c.transport.DoWithContentType(ctx, http.MethodPatch, endpoint, request, "application/json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("UpdateDistributorConfiguration: %w", err)
	}
	return nil
}
