// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package account

import (
	"context"
	"fmt"
	"net/http"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ListLicenses list Licenses.
//
// Required privileges: the spec declares none.
func (c *Client) ListLicenses(ctx context.Context) ([]License, error) {
	prefix := c.transport.APIPrefix("licensing", "v1")
	endpoint := prefix + "/licenses"

	results, err := client.UnwrapResults[License](ctx, c.transport, http.MethodGet, endpoint, "results")
	if err != nil {
		return nil, fmt.Errorf("ListLicenses: %w", err)
	}
	return results, nil
}
